#pragma once

#include "ActorPackage.hpp"
#include "ActorValue.hpp"
#include "BSEnums.hpp"
#include "BSSimpleList.hpp"
#include "Gamebryo/NiPoint3.hpp"
#include "Gamebryo/NiSmartPointer.hpp"

class ActiveEffect;
class AnimIdle;
class ArrowProjectile;
class Actor;
class HitData;
class Animation;
class BGSBodyPartData;
class BGSLoadFormBuffer;
class BGSSaveGameBuffer;
class BSAnimGroupSequence;
class BSBound;
class BSFaceGenAnimationData;
class BSFaceGenNiNode;
class BSShaderPPLightingProperty;
class PathingAvoidNodeArray;
class BSSoundHandle;
class BipedAnim;
class CombatGroup;
class Crime;
class DetectionState;
class ExtraDataList;
class ItemChange;
class KFModel;
class MagicCaster;
class MagicItem;
class MagicTarget;
class MobileObject;
class MuzzleFlash;
class NiAVObject;
class NiNode;
class NiRefObject;
class NiTriShape;
class Projectile;
class SpellItem;
class TESActorBase;
class TESAmmo;
class TESEffectShader;
class TESIdleForm;
class TESObject;
class TESObjectCELL;
class TESObjectWEAP;
class TESTopic;
class TESWorldSpace;
class bhkCharacterController;
class NiControllerManager;
class TESPackageData;
class DialogueItem;
class DetectionEvent;
class ObjectToAcquire;
class LipSynchAnim;
class TESBoundObject;
class TESObjectSTAT;
struct FurnitureMark;

class BaseProcess {
public:
	BaseProcess();

	struct CachedValues {
		struct ALIGN4 _CachedFlags {
			enum Flags : uint32_t {
				RADIUS					= 1u << 0,
				WIDTH					= 1u << 1,
				LENGTH					= 1u << 2,
				WEAPON_DPS				= 1u << 3,
				MEDICINE_SKILL_MULT		= 1u << 4,
				PARALYSIS				= 1u << 5,
				HEALING_RATE			= 1u << 6,
				ENDURANCE				= 1u << 7,
				PERCEPTION_CONDITION	= 1u << 8,
				EYE_LEVEL				= 1u << 9,
				AGGRESSION				= 1u << 10,
				ASSISTANCE				= 1u << 11,
				WALK_SPEED				= 1u << 12,
				RUN_SPEED				= 1u << 13,
				CONDITION_PREVENTS_RUN	= 1u << 14,
				FORWARD_LENGTH			= 1u << 15,

				IS_GHOST				= 1u << 28,
				HEALTH_DAMAGED			= 1u << 29,
				FATIGUE					= 1u << 30,
				SURVIVAL_SKILL_MULT		= 1u << 31
			};

			bool bRadius				: 1;
			bool bWidth					: 1;
			bool bLength				: 1;
			bool bWeaponDPS				: 1;
			bool bMedicineSkillMult		: 1;
			bool bParalysis				: 1;
			bool bHealingRate			: 1;
			bool bEndurance				: 1;
			bool bPerceptionCondition	: 1;
			bool bEyeLevel				: 1;
			bool bAggression			: 1;
			bool bAssistance			: 1;
			bool bWalkSpeed				: 1;
			bool bRunSpeed				: 1;
			bool bConditionPreventsRun	: 1;
			bool bForwardLength			: 1;
			bool						: 4;
			bool						: 4;
			bool						: 4;
			bool bIsGhost				: 1;
			bool bHealthDamaged			: 1;
			bool bFatigueDamaged		: 1;
			bool bSurvivalSkillMult		: 1;
		};
		using CachedFlags = _CachedFlags::Flags;

		float					fCachedRadius;
		float					fCachedWidth;
		float					fCachedLength;
		float					fCachedForwardLength;
		float					fCachedWeaponDPS;
		float					fCachedMedicineEffectivenessMult;
		float					fCachedSurvivalEffectivenessMult;
		float					fCachedParalysis;
		float					fCachedHealingRate;
		float					fCachedEndurance;
		float					fCachedPerceptionCondition;
		float					fCachedEyeLevel;
		int32_t					eCachedActorAggression;
		int32_t					eCachedActorAssistance;
		float					fCachedWalkSpeed;
		float					fCachedRunSpeed;
		bool					bConditionPreventsRun;
		Bitfield<_CachedFlags>	uiFlags;
	};
	using CachedFlags = CachedValues::CachedFlags;

	struct ALIGN1 _Update3DFlags {
		enum Flags : uint8_t {
			UPDATE_MODEL	= 1u << 0,
			UPDATE_SKIN		= 1u << 1,
			UPDATE_HEAD		= 1u << 2,
			UPDATE_FACE		= 1u << 3,
			UPDATE_SCALE	= 1u << 4,
		};

		bool bUpdateModel	: 1;
		bool bUpdateSkin	: 1;
		bool bUpdateHead	: 1;
		bool bUpdateFace	: 1;
		bool bUpdateScale	: 1;
	};
	using Update3DFlags = _Update3DFlags::Flags;

	enum HeadTrackType : uint32_t {
		HEAD_TRACK_TYPE_DEFAULT		= 0,
		HEAD_TRACK_TYPE_ACTION		= 1,
		HEAD_TRACK_TYPE_COMBAT		= 2,
		HEAD_TRACK_TYPE_DIALOG		= 3,
		HEAD_TRACK_TYPE_SCRIPT		= 4,
		HEAD_TRACK_TYPE_PROCEDURE	= 5,
		HEAD_TRACK_TYPE_COUNT		= 6,
	};

	virtual									~BaseProcess();
	virtual void							Copy(BaseProcess* apSource);
	virtual void							HandleDeletedReference(Actor* apActor);
	virtual void							UpdateAlt(MobileObject* apObject, float afDelta);
	virtual void							Update(MobileObject* apObject);
	virtual void							UpdateMissedPackages(MobileObject* apObject, bool abActionflag);
	virtual NiPoint3						GetCurrentPackageLocation(Actor* apActor);
	virtual NiPoint3						GetDetectionLocation(Actor* apActor, int);
	virtual double							GetLastTimeDetected(Actor* apActor, int);
	virtual bool							CheckForNewPackage(Actor* apActor, bool abFlag);
	virtual void							ComputeLastTimeProcessed();
	virtual bool							IsWandering() const;
	virtual uint32_t						GetProcessedDay() const;
	virtual uint32_t						GetProcessedMonth() const;
	virtual uint32_t						GetProcessedYear() const;
	virtual void							SetPackageEvaluateHour(int32_t aiVal);
	virtual int32_t							GetPackageEvaluateHour() const;
	virtual bool							SetupSpecialIdle(Actor* apActor, TESIdleForm* apIdle, uint32_t aeDefaultAction, bool abCrippled, bool abForce, bool abTestConditions);
	virtual void							SetLastSeenLocation();
	virtual MagicItem*						GetCurrentPackageSpell() const;
	virtual void							SetCurrentPackageSpell(MagicItem* apSpell);
	virtual void							PerformOneRoundofCombat(Actor* apActor, uint32_t aeProcessLevel);
	virtual void							ClearFaceAnimationData();
	virtual void							UpdateHealthBar(Actor* apActor);
	virtual bool							GetIdleDoneOnce() const;
	virtual void							SetIdleDoneOnce(bool abVal);
	virtual bool							EvaluateDetection(Actor* apActor);
	virtual void							EvaluateCombatDetectionLists(Actor* apActor);
	virtual bool							ShouldRunPlayerDetection(Actor* apActor) const;
	virtual bool							ProcessActivateOneHour(Actor apActor, float afTimeDelta);
	virtual bool							IsDoingSayTo() const;
	virtual void							ProcessSandman(Actor* apActor);
	virtual void							ProcessCannibal(Actor* apActor);
	virtual void							ClearFurniture(Actor* apActor);
	virtual void							SetDoingSayTo(bool abVal);
	virtual bool							SetTargetForPackage(Actor* apActor);
	virtual bool							SetLocationForPackage(Actor* apActor);
	virtual TESObjectREFR*					GetCurrentDestinationReference(Actor* apActor, bool abInterrupt);
	virtual NiPoint3*						GetCurrentDestinationCoordinate(NiPoint3& arPos, Actor* apActor, bool abInterrupt);
	virtual TESObjectCELL*					GetCurrentDestinationCell(Actor* apActor);
	virtual TESWorldSpace*					GetCurrentDestinationWorldSpace(Actor* apActor);
	virtual float							GetCurrentDestinationRadius(Actor* apActor);
	virtual MobileObject*					GetDialogTarget() const;
	virtual void							ClearDialogTarget();
	virtual bool							CheckAndStartCombatControllerForPackage(Actor* apActor, TESPackage* apPackage, bool abInCombat);
	virtual bool							ShouldUpdateCombatControllerOrEndCombat(Actor* apActor, TESPackage** appPackage);
	virtual float							GetSocialTalkTimer() const;
	virtual void							SetSocialTalkTimer(float afValue);
	virtual void							RemoveSpokenToActor(Actor* apActor);
	virtual void							ProcessRemoveWorn(Actor* apActor, bool abInterateIndex);
	virtual void							CreateFollowforEscort(Actor* apActor, TESPackage* apPackage, bool abCheck);
	virtual bool							GetDetectAlert() const;
	virtual void							SetDetectAlert(bool abVal);
	virtual void							RandomlyPlaySpecialIdles(Actor* apActor);
	virtual void							PostAnimFreeUpSpecialIdle(Actor* apActor);
	virtual void							ResetSearchTimer();
	virtual void							ModEssentialDownTimer();
	virtual float							GetEssentialDownTimer() const;
	virtual void							SetEssentialDownTimer(float afValue);
	virtual void							ResetSearchChatterTimer();
	virtual DetectionState*					InsertIntoDetectionList(Actor* apActor, uint32_t aeDetectionLevel, bool abInLOS, int32_t aiMinDetectionLevel, bool, bool, bool abInCombat);
	virtual BSSimpleList<DetectionState*>*	GetDetectingActors();
	virtual DetectionEvent*					GetActorsDetectionEvent(Actor* apActor);
	virtual void							SetActorsDetectionEvent(Actor* apActor, NiPoint3 akPosition, uint32_t auiSoundLevel, int unused, TESObjectREFR* apRef);
	virtual void							RemoveDetectionEvent();
	virtual void							CheckForExpiredDetectionEvent();
	virtual void							GetWeaponScore();
	virtual void							SetWeaponScore(float afVal);
	virtual bool							GetPickpocketed() const;
	virtual void							SetPickpocketed();
	virtual void							SetCurrentActionComplete(bool abVal);
	virtual bool							GetCurrentActionComplete() const;
	virtual void							SetCurrentMovementComplete(bool abVal);
	virtual bool							GetCurrentMovementComplete() const;
	virtual TESObjectREFR*					GetTarget() const;
	virtual void							SetTarget(TESObjectREFR* apTarget);
	virtual TESObjectREFR*					GetDoor() const;
	virtual void							SetDoor(TESObjectREFR* apDoor);
	virtual void							SetAcquireObject(ObjectToAcquire* apObject);
	virtual ObjectToAcquire*				GetSavedAcquireObject() const;
	virtual void							SetSavedAcquireObject(ObjectToAcquire* apObject);
	virtual BSFaceGenAnimationData*			GetFaceAnimationData();
	virtual ItemChange*						GetCurrentWeapon() const;
	virtual ItemChange*						GetCurrentAmmo() const;
	virtual bool							GetLipQueued() const;
	virtual void							SetLipQueued(bool abVal);
	virtual uint32_t						GetNumberOfItemsActivated() const;
	virtual void							SetNumberOfItemsActivated(uint32_t auiCount);
	virtual bool							SetCurrentWeapon(ItemChange* apWeapon, NiNode* apScene, bool abForce);
	virtual void							SetCurrentTorch(ItemChange* apTorch);
	virtual bool							SetCurrentAmmo(ItemChange* apAmmo);
	virtual void							SetCurrentShield(ItemChange* apShield);
	virtual void							ResolveEquipmentQueue(Actor* apActor);
	virtual bool							IsItemQueued(TESBoundObject* apItem, ExtraDataList* apExtraList, bool abEquip);
	virtual void							AddQueuedItem(Actor* apActor, bool abEquip, TESBoundObject* apItem, int32_t aiEquip, ExtraDataList* apExtraList, bool abNow, bool abForceEquip, bool abFromMenus, bool abForceUnequip, bool abEquipCalling, bool abPlaySound);
	virtual void							RemoveQueuedItem(TESBoundObject* apObject, ExtraDataList* apExtraList);
	virtual void							RemoveAllQueuedItems();
	virtual NiNode*							GetFireNode() const;
	virtual void							SetFireNode(NiAVObject* apNode);
	virtual bool							StoreBonePointers(NiControllerManager* apControllerManager, NiNode* apNode);
	virtual NiNode*							GetWeaponBone(BipedAnim* apAnim) const;
	virtual NiNode*							GetTorchBone(BipedAnim* apAnim) const;
	virtual NiNode*							GetShieldBone(BipedAnim* apAnim) const;
	virtual NiNode*							GetQuiverBone(BipedAnim* apAnim) const;
	virtual NiNode*							GetRightWeaponBone(BipedAnim* apAnim) const;
	virtual NiNode*							GetLeftWeaponBone(BipedAnim* apAnim) const;
	virtual bool							IsCurrentWeaponGrenade() const;
	virtual bool							IsCurrentWeaponMine() const;
	virtual bool							IsCurrentWeaponGrenadeOrMine() const;
	virtual bool							IsCurrentWeaponThrown() const;
	virtual Animation*						GetAnimation() const;
	virtual bool							GetLockedLocation() const;
	virtual void							SetLockedLocation(bool abVal);
	virtual bool							GetIsAggressor() const;
	virtual void							SetIsAggressor(bool abVal);
	virtual void							ForceWeaponDrawnSheathed(bool abDrawn, BipedAnim* apBipedAnim, Animation* apAnim, Actor* apActor);
	virtual void							SetItemBeingUsed(TESObject* apItem);
	virtual TESObject*						GetItemBeingUsed() const;
	virtual void							UpdateReparentWeapon(Actor* apActor);
	virtual void							CreateFollownoEscort(Actor* apActor, bool abFlag);
	virtual float							GetAwarePlayerTimer() const;
	virtual void							ModAwarePlayerTimer(float afVal);
	virtual void							SetCombatDelayFadeTimer(float afVal);
	virtual bool							CheckCombatDelayTimer() const;
	virtual void							AddTalkedtoActor(Actor* apActor);
	virtual bool							ComputeCanInitiateDialogueWithNPC(Actor* apActor, Actor* apTarget) const;
	virtual bool							ComputeCanRespondToDialogueFromNPC(Actor* apActor, Actor* apTarget) const;
	virtual bool							IsActorInsideAmbushArea(Actor* apActor, Actor* apTarget) const;
	virtual bool							CheckIfThereSomeoneTalkWith(Actor* apActor);
	virtual bool							ComputeAllowSandboxConversation(Actor* apActor, Actor* apTarget);
	virtual float							GetPotentialThreatDamage(Actor* apActor, Actor* apTarget);
	virtual TESPackage*						GetRunOncePackage() const;
	virtual void							SetRunOncePackage(TESPackage* apPackage, Actor* apActor);
	virtual void							ClearRunOncePackage();
	virtual void							SetRunOnceProcedureIndex(int32_t aiIndex);
	virtual int32_t							GetRunOnceProcedureIndex() const;
	virtual void							AddToRunOnceProcedureIndex(int32_t aiOffset);
	virtual void							ClearGreetingInfoData();
	virtual bool							IsPackageDone(Actor* apActor) const;
	virtual TESPackage*						GetCurrentPackage() const;
	virtual void							SetCurrentPackage(TESPackage* apPackage, Actor* apActor);
	virtual void							ClearCurrentPackage();
	virtual void							SetCurrentProcedureIndex(int32_t aiIndex);
	virtual int32_t							GetCurrentProcedureIndex() const;
	virtual void							AddToCurrentProcedureIndex(int32_t aiOffset);
	virtual void							SetupNewPackage();
	virtual DialogueItem*					GetSubtitleItem() const;
	virtual void							SetSubtitleItem(DialogueItem* apSubtitle);
	virtual void							AddAvoidPathingArea(Actor* apActor, NiPoint3 akPoint, float afRadius, float afTimeToExpire, float afRadiationLevel, TESObjectREFR* apRef, TESObjectSTAT* apMarker);
	virtual PathingAvoidNodeArray*			CreateAvoidArray();
	virtual bool							IsAvoidAreaInAvoidPathingList(TESObjectREFR* apRef) const;
	virtual void							SetAvoidWaitTimer(float afVal);
	virtual void							RemoveAvoidPathingNode(TESObjectREFR* apRef);
	virtual float							GetHeadTrackChangeTimer() const;
	virtual void							SetHeadTrackChangeTimer(float afVal);
	virtual void							ClearLastHeadTrackTarget();
	virtual ActorPackageData*				GetRunOncePackageInstanceData() const;
	virtual ActorPackageData*				GetInstanceDataThatIsRunning() const;
	virtual ActorPackage*					GetActorPackageThatIsRunning() const;
	virtual TESPackage*						GetPackageThatIsRunning() const;
	virtual int32_t							GetProcedureIndexRunning() const;
	virtual void							SetProcedureIndexRunning(uint32_t aiIndex);
	virtual void							AddToProcedureIndexRunning(Actor* apActor, int32_t aiOffset);
	virtual bhkCharacterController*			GetCharController() const;
	virtual void							SetCharController(NiPointer<bhkCharacterController>& arController);
	virtual void							EndMoveMessage(Actor* apActor);
	virtual void							ProcessFollow(Actor* apActor, bool abFlag, uint32_t aeMoveMode, bool abPursuit);
	virtual void							ProcessPursue(Actor* apActor, bool abNewPackage, bool abInterateIndex, uint32_t aeMoveMode);
	virtual void							ProcessFlee(Actor* apActor);
	virtual void							ProcessGreet(Actor* apActor, TESTopic* apTopic, bool abForceSub, bool abStop, bool abQueue, bool abSayCallBack);
	virtual void							ProcessObserveCombat(Actor* apActor);
	virtual void							ProcessGetUpOneHour(Actor* apActor);
	virtual void							SitOrSleep(Actor* apActor);
	virtual bool							ShouldDisableCharController(TESObjectREFR* apFurnitureRef, uint32_t auiFurnitureType);
	virtual bool							ProcessGetUp(Actor* apActor);
	virtual void							ProcessTravel(Actor* apActor, bool abNewPackage, bool abIterateIndex, uint32_t aeMoveMode, bool abSecondLoc);
	virtual void*							GetWadingWaterData() const;
	virtual void							RemoveDetectionActor(Actor* apActor, uint32_t aeRemoveType);
	virtual void							SetDetectionTimer();
	virtual void							GetLineSightonActor(Actor* apActor, Actor* apTarget, uint32_t aeDetectMode, bool abFullTest);
	virtual bool							Get360LineSightonActor(Actor* apActor, Actor* apTarget, uint32_t aeDetectMode);
	virtual int32_t							GetDetectionActor(Actor* apTarget, uint32_t aeDetectMode) const;
	virtual bool							GetTalkingtoPC() const;
	virtual void							SetTalkingtoPC(bool abVal);
	virtual void							UpdateFollowers(Actor* apActor, float afTimeDelta);
	virtual int								GetEmotionsDispostion(Actor* apActor, TESObjectREFR* apTarget);
	virtual uint32_t						GetLastSpeakingEmotion() const;
	virtual void							SetLastSpeakingEmotion(uint32_t aeEmotion);
	virtual void							RunDetection();
	virtual double							GetDetectionTimer();
	virtual void							ReduceDetectionTimer();
	virtual void							SetBreathTimer(float afVal);
	virtual float							GetBreathTimer() const;
	virtual void							SetSurfacing(bool abVal);
	virtual bool							GetSurfacing();
	virtual bool							GetGreetingFlag() const;
	virtual void							SetGreetingFlag(bool abVal);
	virtual float							GetSoundDelay() const;
	virtual void							SetSoundDelay(float afVal);
	virtual bool							GetAlert() const;
	virtual void							SetAlert(bool abVal);
	virtual bool							GetFinishingCombatPackage();
	virtual void							SetFinishingCombatPackage(bool abVal);
	virtual ItemChange*						CreateWeaponAcquireList(Actor* apActor, uint32_t aePackageObjectType);
	virtual void							ClearAcquireList();
	virtual float							GetIdleTimer() const;
	virtual void							SetIdleTimer(float afValue);
	virtual bool							EnterCombat(Actor* apActor, Actor* apTarget, bool, bool abIsEvil, CombatGroup* apCombatGroup, bool, bool, bool abIsAggressor, bool, bool abIgnoreActorLimit, bool, bool, TESPackage* apPackage);
	virtual void							GuardCallforHelp(Actor* apActor, Actor* apCriminal);
	virtual void							CallForHelp(Actor* apActor, Actor* apCriminal, Crime* apCrime);
	virtual void							SetNumberGuardsArresting(int32_t aiVal);
	virtual uint32_t						CalculateMoveMode(Actor* apActor, float afDistanceSq, float afShortDistSq, float afLongDistSq, bool abAlarmOrCombat, bool abPureTravel) const;
	virtual void							SetActorsAnimation(Actor* apActor, uint32_t aeMoveMode, bool abCheckAlwaysRun);
	virtual void							FinishDying(Actor* apActor);
	virtual bool							ProcessStandOff(Actor* apActor, float afRadius, uint32_t aeMoveMode);
	virtual bool							IsRunningRunOnce() const;
	virtual bool							IsAFollower() const;
	virtual void							SetFollower(bool abVal);
	virtual int32_t							GetWeaponCondition(Actor* apActor);
	virtual bool							GetWaitingforLipFile() const;
	virtual void							SetWaitingforLipFile(bool abVal);
	virtual void							SetLipFileFailed(bool abVal);
	virtual bool							GetLipFileFailed() const;
	virtual LipSynchAnim*					GetLipAnim() const;
	virtual void							SetLipAnim(LipSynchAnim* apAnim);
	virtual void							SetPlantedExplosive(bool abVal);
	virtual bool							GetPlantedExplosive() const;
	virtual TESIdleForm*					GetLastIdlePlayed() const;
	virtual void							SetLastPlayedIdle(TESIdleForm* idleForm);
	virtual void							FreeUpSpecialIdle(Actor* apActor);
	virtual int32_t							GetActorValueI(TESActorBase* apBase, ActorValue::Index aeIndex, Actor* apActor);
	virtual float							GetActorValueF(TESActorBase* apBase, ActorValue::Index aeIndex, Actor* apActor);
	virtual void							TempModActorValueF(Actor* apActor, ActorValue::Index aeIndex, float afVal);
	virtual void							TempModActorValueI(Actor* apActor, ActorValue::Index aeIndex, int32_t aiVal);
	virtual void							DamageModActorValueF(Actor* apActor, ActorValue::Index aeIndex, float afVal);
	virtual void							DamageModActorValueI(Actor* apActor, ActorValue::Index aeIndex, int32_t aiVal);
	virtual void							SetCachedActorValueOutOfDate(ActorValue::Index aeIndex);
	virtual void							InitializeActiveEffectList();
	virtual BSSimpleList<ActiveEffect*>*	GetActiveEffectList() const;
	virtual void							DestroyActiveEffectList();
	virtual void							CastAbility(MagicCaster* apCaster, SpellItem* apAbility, bool abLoadCast);
	virtual void							TransferDisease(MagicCaster* apCaster, SpellItem* apDisease, MagicTarget* apTarget, bool abLoadCast);
	virtual MagicItem*						GetCurrentSpell() const;
	virtual void							SetCurrentSpell(MagicItem* apSpell);
	virtual MagicTarget*					GetDesiredTarget() const;
	virtual void							SetDesiredTarget(MagicTarget* apTarget);
	virtual bool							GetShouldCheckMagicNode() const;
	virtual void							SetShouldCheckMagicNode(bool abVal);
	virtual void							Move(MobileObject*, NiPoint3);
	virtual ANIMATION_ACTION				GetAnimAction() const;
	virtual BSAnimGroupSequence*			GetAnimActionAnimSeq() const;
	virtual void							SetAnimAction(ANIMATION_ACTION aeAnimationAction, BSAnimGroupSequence* apSequence);
	virtual bool							GetAutomaticFireAtLeastOnce() const;
	virtual void							SetAutomaticFireAtLeastOnce(bool abVal);
	virtual bool							CanAttack() const;
	virtual bool							CanForceGreet(Actor* apActor);
	virtual void							SetIronSights(bool isAiming);
	virtual bool							GetIronSights() const;
	virtual bool							HasMovementAnim(ANIM_GROUP aeAnim);
	virtual int32_t							GetKnockedState();
	virtual void							SetKnockedState(char state);
	virtual void							KnockDown(Actor* apActor);
	virtual void							KnockExplosion(Actor* apActor, NiPoint3 akSource, float afForce);
	virtual void							UpdateKnockState(Actor* apActor);
	virtual void							ClearKnockState(Actor* apActor);
	virtual void							SetAimSequence(uint32_t aeDirection, BSAnimGroupSequence* apSequence);
	virtual void							UpdateAimSequences(Actor* apActor);
	virtual float							GetAimLooking() const;
	virtual void							AddGunDrift(float afValue);
	virtual void							ClearAutomaticShotsToFire(bool abStartShooting);
	virtual uint8_t							GetAutomaticShotsToFire(Actor* apTarget);
	virtual void							SetShotsToFire(uint8_t aucCount);
	virtual uint8_t							GetShotsToFire() const;
	virtual float							GetAutomaticShotDelay() const;
	virtual void							AttackCallback(int32_t aiNumAttacks);
	virtual bool							GetWantWeaponDrawn() const;
	virtual void							SetWantWeaponDrawn(bool abVal);
	virtual bool							GetWeaponDrawn() const;
	virtual void							SetWeaponDrawn(Actor* apActor, bool abVal);
	virtual void							SetWeaponLastPos(NiPoint3 akPos);
	virtual NiPoint3*						GetWeaponLastPos() const;
	virtual void							Update3DModel(Actor* apActor);
	virtual void							Set3DUpdateFlag(uint8_t aucFlag);
	virtual void							Clear3DUpdateFlag(uint8_t aucFlag);
	virtual void							ClearAll3DUpdateFlags();
	virtual bool							Get3DUpdateFlag(uint8_t aucFlag) const;
	virtual uint8_t							GetAll3DUpdateFlags() const;
	virtual void							ClearObjectFromAcquireList(TESObjectREFR* apObject);
	virtual void							ClearObjectFromAcquireListAlt(uint32_t auiFormID);
	virtual TESObjectREFR*					GetLastGreeted() const;
	virtual void							SetLastGreeted(TESObjectREFR* apRef);
	virtual BSSoundHandle					GetSoundHandle(uint32_t aeType);
	virtual void							SetSoundHandle(uint32_t aeType, BSSoundHandle akHandle);
	virtual void							StopSoundHandle(uint32_t aeType);
	virtual void							StartTorchSound(Actor* apActor);
	virtual bool							GetMovementStopped() const;
	virtual void							ClearMovementStopped();
	virtual void							SetDetectionModifier(float afVal);
	virtual void							SetDetectionModifierTimer();
	virtual float							GetDetectionModifier() const;
	virtual float							GetGreetingTimer() const;
	virtual void							SetGreetingTimer(float afVal);
	virtual bool							IsTalking() const;
	virtual uint32_t						GetSitSleepState() const;
	virtual void							SetSitSleepState(Actor* apActor, uint32_t aeState, TESObjectREFR* apFurniture, uint8_t aucFurnitureIndex);
	virtual uint32_t						GetFurnitureMarkerID() const;
	virtual TESObjectREFR*					GetCurrentFurniture() const;
	virtual void							RemoveFurniture(TESObjectREFR* apFurnitureRef);
	virtual uint32_t						GetCurrentFurnitureIndex() const;
	virtual FurnitureMark*					GetFurnitureMarker() const;
	virtual bool							LoadDynamicIdle(Actor* apActor);
	virtual void							LoadSitSleepIdle(Actor* apActor, Animation* apAnimation);
	virtual bool							ContinuingPackageforPC() const;
	virtual void							SetContinuingPackage(bool abVal);
	virtual bool							IsTargetActivated() const;
	virtual void							SetTargetActivated();
	virtual bool							HasBeenAttacked() const;
	virtual void							SetBeenAttacked(bool abVal);
	virtual BSShaderPPLightingProperty*		GetLightingShaderProperty() const;
	virtual void							SetLightingShaderProperty(BSShaderPPLightingProperty* apProp);
	virtual void							CalculateLightValue(Actor* apActor, bool abIgnoreTorch);
	virtual DetectionState*					GetDetectionState(Actor* apTarget, uint32_t aeListType);
	virtual DetectionState*					InsertIntoDetectionArray(Actor* apTarget, uint32_t auiDetectionLevel);
	virtual double							GetLightUpdateTimer() const;
	virtual void							SetLightUpdateTimer(float afVal);
	virtual TESObjectREFR*					GetGenericLocation() const;
	virtual void							SetGenericLocation(TESObjectREFR* apLocation);
	virtual TESObjectREFR*					GetSecondGenericLocation() const;
	virtual void							SetSecondGenericLocation(TESObjectREFR* apLocation);
	virtual void							ClearCurrentDataforProcess();
	virtual void							SetCommandingActor(Actor* apActor);
	virtual Actor*							GetCommandingActor() const;
	virtual void							SetLastBoundWeapon(TESObjectWEAP* apWeapon);
	virtual TESObjectWEAP*					GetLastBoundWeapon() const;
	virtual void							SetPackageEndTimerValue(float afVal);
	virtual float							GetPackageEndTimerValue() const;
	virtual void							SetFurniture(TESObjectREFR* apFurnitureRef, uint8_t aucMarkerIndex, FurnitureMark* apMark);
	virtual void							RemoveAndAttachItems(MobileObject* apObject);
	virtual uint16_t						GetSaveSize(uint32_t auiFlags, MobileObject* apObject);
	virtual void							SaveGameBGS(BGSSaveGameBuffer* apBuffer);
	virtual void							SaveGameTES(uint32_t auiFlags, MobileObject* apObject);
	virtual void							LoadGameBGS(BGSLoadFormBuffer* apBuffer);
	virtual void							LoadGameTES(uint32_t auiFlags, uint32_t auiCurrentFlags, MobileObject* apObject);
	virtual void							InitLoadGameBGS(BGSLoadFormBuffer* apBuffer);
	virtual void							InitLoadGameTES(uint32_t auiFlags, uint32_t auiOldFlags, MobileObject* apObject);
	virtual void							FinishInitLoadGame(uint32_t auiFlags, uint32_t auiOldFlags, MobileObject* apObject);
	virtual void							RevertBGS(BGSLoadFormBuffer* apBuffer);
	virtual void							RevertTES(uint32_t auiFlags, MobileObject* apObject);
	virtual void							FinishLoadGame();
	virtual TESEffectShader					GetWeaponEnchantmentVisuals() const;
	virtual void							SetWeaponEnchantmentVisuals(TESEffectShader* apShader);
	virtual bool							GetShouldRefreshMagicShadersEffects() const;
	virtual void							SetShouldRefreshMagicShadersEffects(bool abUpdateWeaponEffectShader, bool abInitializeActiveHitEffect, bool);
	virtual void							RefreshMagicShaderEffects(Actor* apActor);
	virtual void							SetBeginIdlesPlayed(bool abVal);
	virtual bool							GetBeginIdlesPlayed() const;
	virtual void							SetEndIdlesPlayed(uint8_t aucVal);
	virtual bool							GetEndIdlesPlayed() const;
	virtual void							StartNewPackage(Actor *apActor, TESPackage *apPackage);
	virtual TESPackage*						ChangePackage(Actor *apActor, TESPackage *apPackage);
	virtual void							PackageDone(Actor *apActor, TESPackage *apPackage);
	virtual bool							IsPackageDoneOnce() const;
	virtual void							SetPackageDoneOnce(bool abVal);
	virtual float							GetAlphaMult() const;
	virtual void							SetAlphaMult(float afVal);
	virtual float							GetScriptRefractionPower() const;
	virtual void							SetScriptRefractionPower(float afVal);
	virtual void							UpdateWadingWater(Actor* apActor);
	virtual int32_t							GetNumberGuardsArresting() const;
	virtual void							ModNumberGuardsArresting(int32_t aiVal);
	virtual bool							ShouldCheckFlare(BSSimpleList<ActiveEffect*>* apEffects, uint32_t aeFlareType);
	virtual void							SetRefreshFlareFlags();
	virtual BSSimpleList<SpellItem*>*		GetLeveledSpells(Actor* apActor, bool abIncludeDiseases);
	virtual void							SetHasHealingSpells(int32_t aiHasSpells);
	virtual int32_t							GetHasHealingSpells() const;
	virtual void							SetHasHealingPotions(int32_t);
	virtual int32_t							GetHasHealingPotions() const;
	virtual float							GetTemporaryModifier(uint8_t aeActorValue);
	virtual float							GetPermanentModifier(uint8_t aeActorValue);
	virtual float							GetDamageModifier(uint8_t aeActorValue);
	virtual BSBound*						GetBound() const;
	virtual void							SetBound(BSBound* apBound);
	virtual void							SetForceNextUpdate(bool abVal);
	virtual bool							GetForceNextUpdate() const;
	virtual void							SetNeedTalkPlayer(bool abVal);
	virtual bool							GetNeedTalkPlayer() const;
	virtual BSSimpleList<Actor*>*			GetActorsInAggroRadius() const;
	virtual void							NotifyGuardAboutActivation(Actor* apActor, Actor* apTarget, Actor* apAlly);
	virtual uint32_t						GetFadeState() const;
	virtual void							AddPostAnimationAction(uint32_t auiFlag);
	virtual uint32_t						GetPostAnimationActions() const;
	virtual void							ClearPostAnimationActions();
	virtual void							RemovePostAnimationAction(uint32_t auiFlag);
	virtual void							SetDefaultHeadTrackTarget(TESObjectREFR* apTarget);
	virtual void							SetActionHeadTrackTarget(TESObjectREFR* apTarget);
	virtual void							SetScriptHeadTrackTarget(TESObjectREFR* apTarget);
	virtual void							SetCombatHeadTrackTarget(TESObjectREFR* apTarget);
	virtual void							SetDialogHeadTrackTarget(TESObjectREFR* apTarget);
	virtual void							SetUseWeaponHeadTrackTarget(TESObjectREFR* apTarget);
	virtual void							SetHeadTrackTarget(HeadTrackType aeType, TESObjectREFR* apTarget);
	virtual void							ClearDefaultHeadTrackTarget();
	virtual void							ClearActionHeadTrackTarget(bool abHoldDefault);
	virtual void							ClearScriptHeadTrackTarget(bool abHoldDefault);
	virtual void							ClearCombatHeadTrackTarget();
	virtual void							ClearDialogHeadTrackTarget(bool abHoldDefault);
	virtual void							ClearUseWeaponHeadTrackTarget(bool abHoldDefault);
	virtual void							ModDetectionModifierTimer();
	virtual float							GetDetectionModifierTimer() const;
	virtual void							ResetHeadTrackingTarget();
	virtual void							RemoveHeadTrackTarget(TESObjectREFR* apTarget);
	virtual bool							CanSetDefaultHeadTrackTarget();
	virtual bool							CanSetActionHeadTrackTarget();
	virtual bool							CanSetDialogHeadTrackTarget();
	virtual TESObjectREFR*					GetCurrentHeadTrackTargetByType(HeadTrackType aeType);
	virtual TESObjectREFR*					GetCurrentHeadTrackTarget();
	virtual uint32_t						GetCurrentHeadTrackType() const;
	virtual const char*						GetCurrentHeadTrackTypeString() const;
	virtual void							SetForceRotate(bool abVal);
	virtual bool							GetForceRotate() const;
	virtual TESObjectREFR*					GetLastHeadTrackTarget() const;
	virtual bool							IsInLastDefaultTargetArray(TESObjectREFR* apRef);
	virtual void							SetIsSummonedCreature(bool abVal);
	virtual bool							GetIsSummonedCreature() const;
	virtual float							GetDeathTime() const;
	virtual void							SetDeathTime(float afVal);
	virtual void							AddAttachedArrow(ArrowProjectile* apArrow);
	virtual void							RemoveAttachedArrow(ArrowProjectile* apArrow);
	virtual void							MoveAttachedArrowsToParentCell(TESObjectREFR* apRef);
	virtual BSSimpleList<ArrowProjectile*>* GetAttachedArrowList() const;
	virtual void							CreateMuzzleFlash(Projectile* apProjectile, TESObjectREFR* apShooter);
	virtual MuzzleFlash*					GetCurrentMuzzleFlash() const;
	virtual bool							GetEnableMuzzleFlash();
	virtual void							EnableMuzzleFlash();
	virtual void							ClearMuzzleFlash();
	virtual void							StoreDamageNodes(NiNode* apNode, BGSBodyPartData* apBodyPartData);
	virtual void							StoreDismemberedLimbNode(uint32_t aeBodyPart, NiNode* apNode);
	virtual NiNode*							GetDamageNode(uint32_t aeBodyPart) const;
	virtual NiNode*							GetHeadNode() const;
	virtual NiNode*							GetTorsoNode() const;
	virtual bool							GetSustainedFire() const;
	virtual void							SetSustainedFire(bool abVal);
	virtual void							UpdateArmorWorn();
	virtual void							IsWearingHeavyArmor();
	virtual bool							IsWearingPowerArmorTorso();
	virtual bool							IsWearingPowerArmorHelmet();
	virtual bool							IsWearingBackpack();
	virtual void							SetCurrentlyReanimating(bool abVal);
	virtual bool							GetCurrentlyReanimating() const;
	virtual void							UpdateRadiation(Actor* apActor, float afTimeDelta);
	virtual void							TryReserveProjectileClones(Actor* apActor);
	virtual void							SetAnimActionSuccess(int32_t);
	virtual void							FinishSetupSpecialIdle(Actor* apActor);
	virtual void							SavePackageToExtraData(TESObjectREFR* apRef);
	virtual void							LoadPackageFromExtraData(TESObjectREFR* apRef);
	virtual TESIdleForm*					GetCurrentProcessIdle() const;
	virtual void							SetCurrentProcessIdle(TESIdleForm* apIdleForm);
	virtual void							SetCurrentProcessAnimIdleLoaded(AnimIdle* apAnimIdle, KFModel* apAnimIdleKF);
	virtual AnimIdle*						GetCurrentProcessAnimIdle() const;
	virtual KFModel*						GetCurrentProcessAnimIdleKF() const;
	virtual void							ModTrackedDamage(Actor* apSource, float afDamage);
	virtual float							GetTrackedDamage() const;
	virtual float							GetActorLightLevel() const;
	virtual void							SetActorLightLevel(float afLightAmount);
	virtual void							DeferHideDismemberedLimb(uint32_t aeLimbIndex, NiNode* apDismemberedLimbRoot, NiAVObject* apReplacementLimb, bool abExplosion);
	virtual void							UpdateDeferredHideDismemberedLimbs(Actor* apActor, float afTimeDelta);
	virtual void							SetCreatureLipSynchAnim(LipSynchAnim* apAnim);
	virtual LipSynchAnim*					GetCreatureLipSynchAnim() const;
	virtual void							SetCreatureLipSynchStartTime(uint32_t auiTime);
	virtual uint32_t						GetCreatureLipSynchStartTime() const;
	virtual void							AddRadiationMagicDelta(float afVal);
	virtual void							RemoveRadiationMagicDelta(float afVal);
	virtual float							GetRadiationMagicDelta() const;
	virtual void							SetRadiationWaterDelta(float afVal);
	virtual float							GetRadiationWaterDelta() const;
	virtual void							SetRadiationDelta(float afVal);
	virtual float							GetRadiationDelta() const;
	virtual HitData*						GetLastHitData() const;
	virtual void							SetLastHitData(HitData* apHitData);
	virtual void							ClearLastHitData();
	virtual HitData*						GetLastAttackHitData();
	virtual void							SetLastAttackHitData(HitData* apHitData);
	virtual void							ClearLastAttackHitData();
	virtual uint32_t						GetWeaponConditionStage() const;
	virtual void							SetWeaponConditionStage(uint32_t auiHealth);
	virtual BSFaceGenNiNode*				GetFaceNode() const;
	virtual void							SetFaceNode(BSFaceGenNiNode* apNode);
	virtual BSFaceGenNiNode*				GetFaceSkinnedNode() const;
	virtual void							SetFaceSkinnedNode(BSFaceGenNiNode* apNode);
	virtual NiAVObject*						GetHeadAnims() const;
	virtual void							SetHeadAnims(NiAVObject* apObject);
	virtual void							CheckCachedValueFlags(Actor* apActor);
	virtual void							SetPathLookAtTarget(TESObjectREFR* apTarget);
	virtual void							ClearPathLookTarget(TESObjectREFR* apTarget);

	ActorPackage	kCurrentPackage;
	float			fSystemTimeClock;
	float			fHourLastProcessed;
	uint32_t		uiDateLastProcessed;	
	int32_t			eProcessLevel;
	CachedValues*	pCachedValues;

	PROCESS_TYPE GetProcessLevel() const;

	float GetLastTimeProcessed() const;

	bool GetCachedFlag(uint32_t auiFlag) const;
	void SetCachedFlag(uint32_t auiFlag, bool abSet);

	void GetLastProcessedDate(uint32_t& arDay, uint32_t& arMonth, uint32_t& arYear) const;
};

ASSERT_SIZE(BaseProcess, 0x30);