#pragma once

class Actor;

class BGSEntryPoint {
public:
	enum EntryPointType : uint32_t {
		CALCULATE_WEAPON_DAMAGE = 0x0,
		CALCULATE_MY_CRITICAL_HIT_CHANCE = 0x1,
		CALCULATE_MY_CRITICAL_HIT_DAMAGE = 0x2,
		CALCULATE_WEAPON_ATTACK_AP_COST = 0x3,
		CALCULATE_MINE_EXPLODE_CHANCE = 0x4,
		ADJUST_RANGE_PENALTY = 0x5,
		ADJUST_LIMB_DAMAGE = 0x6,
		CALCULATE_WEAPON_RANGE = 0x7,
		CALCULATE_TO_HIT_CHANCE = 0x8,
		ADJUST_EXPERIENCE_POINTS = 0x9,
		ADJUST_GAINED_SKILL_POINTS = 0xA,
		ADJUST_BOOK_SKILL_POINTS = 0xB,
		MODIFY_RECOVERED_HEALTH = 0xC,
		CALCULATE_INVENTORY_AP_COST = 0xD,
		GET_DISPOSITION = 0xE,
		GET_SHOULD_ATTACK = 0xF,
		GET_SHOULD_ASSIST = 0x10,
		CALCULATE_BUY_PRICE = 0x11,
		GET_BAD_KARMA = 0x12,
		GET_GOOD_KARMA = 0x13,
		IGNORE_LOCKED_TERMINAL = 0x14,
		ADD_LEVELED_LIST_ON_DEATH = 0x15,
		GET_MAX_CARRY_WEIGHT = 0x16,
		MODIFY_ADDICTION_CHANCE = 0x17,
		MODIFY_ADDICTION_DURATION = 0x18,
		MODIFY_POSITIVE_CHEM_DURATION = 0x19,
		ADJUST_DRINKING_RADIATION = 0x1A,
		ACTIVATE = 0x1B,
		MYSTERIOUS_STRANGER = 0x1C,
		HAS_PARALYZING_PALM = 0x1D,
		HACKING_SCIENCE_BONUS = 0x1E,
		IGNORE_RUNNING_DURING_DETECTION = 0x1F,
		IGNORE_BROKEN_LOCK = 0x20,
		HAS_CONCENTRATED_FIRE = 0x21,
		CALCULATE_GUN_SPREAD = 0x22,
		PLAYER_KILL_AP_REWARD = 0x23,
		MODIFY_ENEMY_CRITICAL_HIT_CHANCE = 0x24,
		RELOAD_SPEED = 0x25,
		EQUIP_SPEED = 0x26,
		ACTION_POINT_REGEN = 0x27,
		ACTION_POINT_COST = 0x28,
		MISS_FORTUNE = 0x29,
		MODIFY_RUN_SPEED = 0x2A,
		MODIFY_ATTACK_SPEED = 0x2B,
		MODIFY_RADIATION_CONSUMED = 0x2C,
		HAS_PIP_HACKER = 0x2D,
		HAS_MELTDOWN = 0x2E,
		SEE_ENEMY_HEALTH = 0x2F,
		HAS_JURY_RIGGING = 0x30,
		MODIFY_THREAT_RANGE = 0x31,
		MODIFY_THREAT = 0x32,
		HAS_FAST_TRAVEL_ALWAYS = 0x33,
		KNOCKDOWN_CHANCE = 0x34,
		MODIFY_WEAPON_STRENGTH_REQ = 0x35,
		MODIFY_AIMING_MOVE_SPEED = 0x36,
		MODIFY_LIGHT_ITEMS = 0x37,
		MODIFY_DAMAGE_THRESHOLD_DEFENDER = 0x38,
		MODIFY_CHANCE_FOR_AMMO_ITEM = 0x39,
		MODIFY_DAMAGE_THRESHOLD_ATTACKER = 0x3A,
		MODIFY_THROWING_VELOCITY = 0x3B,
		CHANCE_FOR_ITEM_ON_FIRE = 0x3C,
		HAS_UNARMED_FORWARD_POWER_ATTACK = 0x3D,
		HAS_UNARMED_BACK_POWER_ATTACK = 0x3E,
		HAS_UNARMED_CROUCHED_POWER_ATTACK = 0x3F,
		HAS_UNARMED_COUNTER_ATTACK = 0x40,
		HAS_UNARMED_LEFT_POWER_ATTACK = 0x41,
		HAS_UNARMED_RIGHT_POWER_ATTACK = 0x42,
		VATS_HELPER_CHANCE = 0x43,
		MODIFY_ITEM_DAMAGE = 0x44,
		HAS_IMPROVED_DETECTION = 0x45,
		HAS_IMPROVED_SPOTTING = 0x46,
		HAS_IMPROVED_ITEM_DETECTION = 0x47,
		ADJUST_EXPLOSION_RADIUS = 0x48,
		ADJUST_HEAVY_WEAPON_WEIGHT = 0x49,
	};

	struct EntryPointParameter {
		const char* pParameterName;
	};

	struct EntryPointParameters {
		uint32_t				uiCount;
		EntryPointParameter*	pParameters;
	};

	struct EntryPoint {
		const char*				pEntryPointName;
		EntryPointParameters	kFilterParameters;
		uint8_t					ucFunctionType;
	};


	template<typename... Args>
	static void HandleEntryPoint(BGSEntryPoint::EntryPointType aeEntryPoint, Actor* apPerkOwner, Args ...args) {
		((void(__cdecl*)(BGSEntryPoint::EntryPointType, Actor* ,Args...))0x5E58F0)(aeEntryPoint, apPerkOwner, std::forward<Args>(args)...);
	}
};

using BGSEntryPointType = BGSEntryPoint::EntryPointType;