#pragma once

#pragma region Forms

struct _FormType {
	enum Type : uint32_t {
		None = 0,
		TES4,
		Group,
		GameSetting,
		BGSTextureSet,
		BGSMenuIcon,
		TESGlobal,
		TESClass,
		TESFaction,
		BGSHeadPart,
		TESHair,
		TESEyes,
		TESRace,
		TESSound,
		BGSAcousticSpace,
		TESSkill,
		EffectSetting,
		Script,
		TESLandTexture,
		EnchantmentItem,
		SpellItem,
		TESObjectACTI,
		BGSTalkingActivator,
		BGSTerminal,
		TESObjectARMO,
		TESObjectBOOK,
		TESObjectCLOT,
		TESObjectCONT,
		TESObjectDOOR,
		IngredientItem,
		TESObjectLIGH,
		TESObjectMISC,
		TESObjectSTAT,
		BGSStaticCollection,
		BGSMovableStatic,
		BGSPlaceableWater,
		TESGrass,
		TESObjectTREE,
		TESFlora,
		TESFurniture,
		TESObjectWEAP,
		TESAmmo,
		TESNPC,
		TESCreature,
		TESLevCreature,
		TESLevCharacter,
		TESKey,
		AlchemyItem,
		BGSIdleMarker,
		BGSNote,
		BGSConstructibleObject,
		BGSProjectile,
		TESLevItem,
		TESWeather,
		TESClimate,
		TESRegion,
		NavMeshInfoMap,
		TESObjectCELL,
		TESObjectREFR,
		Character,
		Creature,
		MissileProjectile,
		GrenadeProjectile,
		BeamProjectile,
		FlameProjectile,
		TESWorldSpace,
		TESObjectLAND,
		NavMesh,
		TLOD,
		TESTopic,
		TESTopicInfo,
		TESQuest,
		TESIdleForm,
		TESPackage,
		TESCombatStyle,
		TESLoadScreen,
		TESLevSpell,
		TESObjectANIO,
		TESWaterForm,
		TESEffectShader,
		TOFT,
		BGSExplosion,
		BGSDebris,
		TESImageSpace,
		TESImageSpaceModifier,
		BGSListForm,
		BGSPerk,
		BGSBodyPartData,
		BGSAddonNode,
		ActorValueInfo,
		BGSRadiationStage,
		BGSCameraShot,
		BGSCameraPath,
		BGSVoiceType,
		BGSImpactData,
		BGSImpactDataSet,
		TESObjectARMA,
		BGSEncounterZone,
		BGSMessage,
		BGSRagdoll,
		BGSDefaultObjectManager,
		BGSLightingTemplate,
		BGSMusicType,
		TESObjectIMOD,
		TESReputation,
		ContinuousBeamProjectile,
		TESRecipe,
		TESRecipeCategory,
		TESCasinoChips,
		TESCasino,
		TESLoadScreenType,
		MediaSet,
		MediaLocationController,
		TESChallenge,
		TESAmmoEffect,
		TESCaravanCard,
		TESCaravanMoney,
		TESCaravanDeck,
		BGSDehydrationStage,
		BGSHungerStage,
		BGSSleepDeprevationStage,
		Count
	};
};
using FORM_TYPE = _FormType::Type;	

#pragma endregion

#pragma region AI

struct _ProcessType {
	enum Type {
		INVALID			= -1,
		HIGH			= 0,
		MIDDLE_HIGH		= 1,
		MIDDLE_LOW		= 2,
		LOW				= 3,
		COUNT,
	};
};
using PROCESS_TYPE = _ProcessType::Type;

#pragma endregion

#pragma region Packages

struct _PackageLocationType {
	enum Type {
		NONE				= -1,
		REFERENCE			= 0,
		CELL				= 1,
		CURRENT_LOCATION	= 2,
		EDITOR_LOCATION		= 3,
		OBJECT				= 4,
		TYPE				= 5,
		LINKED_REFERENCE	= 6,
		COUNT,
	};
};
using PACKAGE_LOCATION_TYPE = _PackageLocationType::Type;

struct _PackageTargetType {
	enum Type {
		NONE			= -1,
		REFERENCE		= 0,
		OBJECT			= 1,
		TYPE			= 2,
		LINKEDREF		= 3,
	};
};
using PACKAGE_TARGET_TYPE = _PackageTargetType::Type;

struct _PackageObjectType {
	enum Type {
		NONE = 0,
		ACTIVATOR,
		ARMOR,
		BOOK,
		CLOTHING_OLD,
		CONTAINER,
		DOOR,
		INGREDIENT,
		LIGHT,
		MISC,
		FLORA,
		FURNITURE,
		WEAPON,
		AMMO,
		NPC,
		CREATURE,
		KEY,
		ALCHEMY,
		FOOD,
		CLOTHING,
		WEAR,
		WEAPON_RANGED,
		WEAPON_MELEE,
		WEAPON_NONE,
		SPELL,
		SPELL_RANGED,
		SPELL_TOUCH,
		SPELL_SELF,
		ACTOR,
		COUNT,
	};
};
using PACKAGE_OBJECT_TYPE = _PackageObjectType::Type;

struct _PackageType {
	enum Type {
		NONE						= -1,
		EXPLORE						= 0,
		FOLLOW						= 1,
		ESCORT						= 2,
		EAT							= 3,
		SLEEP						= 4,
		WANDER						= 5,
		TRAVEL						= 6,
		ACCOMPANY					= 7,
		USE_ITEM_AT					= 8,
		AMBUSH						= 9,
		FLEE_NON_COMBAT				= 10,
		CAST_MAGIC					= 11,
		SANDBOX						= 12,
		PATROL						= 13,
		GUARD						= 14,
		DIALOGUE					= 15,
		USE_WEAPON					= 16,
		FIND						= 17,
		COMBAT						= 18,
		COMBAT_LOW					= 19,
		ACTIVATE					= 20,
		ALARM						= 21,
		FLEE						= 22,
		TRESPASS					= 23,
		SPECTATOR					= 24,
		REACT_TO_DEAD				= 25,
		GET_UP						= 26,
		DO_NOTHING					= 27,
		IN_GAME_DIALOGUE			= 28,
		SURFACE						= 29,
		SEARCH_FOR_ATTACKER			= 30,
		AVOID_RADIATION				= 31,
		REACT_TO_DESTROYED_OBJECT	= 32,
		REACT_TO_GRENADE_OR_MINE	= 33,
		STEAL_WARNING				= 34,
		PICKPOCKET_WARNING			= 35,
		MOVEMENT_BLOCKED			= 36,
		SANDMAN						= 37,
		CANNIBAL					= 38,
		BACKUP						= 39,
		COUNT,
	};
};
using PACKAGE_TYPE = _PackageType::Type;

struct _PackageProcedureType {
	enum Type {
		NONE					= -1,
		EXPLORE_TRAVEL			= 0,
		EXPLORE_WANDER			= 1,
		EXPLORE_ACTIVATE		= 2,
		EXPLORE_ACQUIRE			= 3,
		SLEEP					= 4,
		EAT						= 5,
		FOLLOW_WITH_ESCORT		= 6,
		AMBUSH_FOLLOW			= 7,
		ESCORT_ACTOR			= 8,
		ESCORT_OBJECT			= 9,
		DIALOGUE				= 10,
		ALARM					= 11,
		COMBAT					= 12,
		ACTIVATE				= 13,
		GREET					= 14,
		OBSERVE_COMBAT			= 15,
		OBSERVE_DIALOGUE		= 16,
		GREET_DEAD				= 17,
		PURSUE_COMBAT			= 18,
		FLEE					= 19,
		TRESPASS				= 20,
		GET_UP					= 21,
		EXPLORE_NPC				= 22,
		MOUNT					= 23,
		DISMOUNT				= 24,
		DO_NOTHING				= 25,
		EXPLORE_ACQUIRE_GENERIC	= 26,
		ACCOMPANY				= 27,
		USEITEMAT				= 28,
		VAMPIRE_FEED			= 29,
		AMBUSH					= 30,
		SURFACE					= 31,
		FLEE_NON_COMBAT			= 32,
		SEARCH					= 33,
		CLEAR_MOUNT_POSITION	= 34,
		SUMMON_CREATURE_DEFEND	= 35,
		AVOID_RADIATION			= 36,
		SANDBOX					= 37,
		PATROL					= 38,
		BUMP_REACTION			= 39,
		GRENADE_MINE_REACTION	= 40,
		GUARD					= 41,
		STEAL_WARN				= 42,
		PICKPOCKET_WARN			= 43,
		USEWEAPON				= 44,
		FOLLOW_WITHOUT_ESCORT	= 45,
		MOVEMENT_BLOCKED		= 46,
		CANNIBAL				= 47,
		BACKUP					= 48,
		COUNT,
	};
};
using PACKAGE_PROCEDURE_TYPE = _PackageProcedureType::Type;

struct _Procedure {
	enum Type {
		NONE						= -1,
		TRAVEL						= 0,
		WANDER						= 1,
		ACTIVATE					= 2,
		ACQUIRE						= 3,
		SLEEP						= 4,
		EAT							= 5,
		FOLLOW						= 6,
		ESCORT						= 7,
		ALARM						= 8,
		COMBAT						= 9,
		FLEE						= 10,
		YIELD						= 11,
		DIALOGUE					= 12,
		WAIT						= 13,
		TRAVEL_TARGET				= 14,
		PURSUE						= 15,
		GREET						= 16,
		CREATE_FOLLOW				= 17,
		OBSERVE_COMBAT				= 18,
		OBSERVE_DIALOGUE			= 19,
		GREET_DEAD					= 20,
		WARN						= 21,
		GET_UP						= 22,
		MOUNT_HORSE					= 23,
		DISMOUNT_HORSE				= 24,
		DO_NOTHING					= 25,
		NOTIFY						= 26,
		ACCOMPANY					= 27,
		USE_ITEM_AT					= 28,
		FEED						= 29,
		AMBUSH_WAIT					= 30,
		SURFACE						= 31,
		WAIT_FOR_SPELL				= 32,
		CHOOSE_CAST					= 33,
		FLEE_NON_COMBAT				= 34,
		REMOVE_WORN_ITEMS			= 35,
		SEARCH						= 36,
		CLEAR_MOUNT_POSITION		= 37,
		SUMMON_CREATURE_DEFEND		= 38,
		AVOID_RADIATION				= 39,
		UNEQUIP_ARMOR				= 40,
		TAKE_BACK_ITEM				= 41,
		SANDBOX						= 42,
		USE_IDLE_MARKER				= 43,
		PATROL						= 44,
		EXPLOSION_REACTION			= 45,
		GRENADE_MINE_PICKUP_THROW	= 46,
		GUARD						= 47,
		ALERT_SEARCH				= 48,
		DIALOGUE_ACTIVATE			= 49,
		USE_WEAPON					= 50,
		MOVEMENT_BLOCKED			= 51,
		CANNIBAL_FEED				= 52,
		BACK_UP						= 53,
		DONE						= 54,
		COUNT						= 54
	};
};
using PROCEDURE = _Procedure::Type;

#pragma endregion

#pragma region Animations

struct _AnimationAction {
	enum Action {
		NONE = -1,
		EQUIP_WEAPON,
		UNEQUIP_WEAPON,
		ATTACK,
		ATTACK_EJECT,
		ATTACK_FOLLOW_THROUGH,
		ATTACK_THROW,
		ATTACK_THROW_ATTACH,
		BLOCK,
		RECOIL,
		RELOAD,
		STAGGER,
		DODGE,
		LOWER_BODY_ANIM,
		SPECIAL_IDLE,
		SCRIPT_ANIMATION,
		RELOAD_LOOP_START,
		RELOAD_LOOP_END,
		RELOAD_LOOP,
	};
};
using ANIMATION_ACTION = _AnimationAction::Action;

enum ANIM_GROUP_MOVE_ENUM : uint16_t {
	ANIM_GROUP_MOVE_NONE	= 0,
	ANIM_GROUP_MOVE_SNEAK	= 1,
	ANIM_GROUP_MOVE_SWIM	= 2,
	ANIM_GROUP_MOVE_FLY		= 3,
};

enum ANIM_GROUP_WEAPON_ENUM : uint16_t {
	ANIM_GROUP_WEAPON_H2H,
	ANIM_GROUP_WEAPON_1HM,
	ANIM_GROUP_WEAPON_2HM,
	ANIM_GROUP_WEAPON_1HP,
	ANIM_GROUP_WEAPON_2HA,
	ANIM_GROUP_WEAPON_2HH,
	ANIM_GROUP_WEAPON_2HL,
	ANIM_GROUP_WEAPON_1GT,
	ANIM_GROUP_WEAPON_1MD,
	ANIM_GROUP_WEAPON_1LM,
};

enum ANIM_GROUP_ENUM : int16_t {
	ANIM_GROUP_NONE = -1,
	ANIM_GROUP_IDLE = 0,
	ANIM_GROUP_DYNAMIC_IDLE,
	ANIM_GROUP_SPECIAL_IDLE,
	ANIM_GROUP_MOVE_FORWARD,
	ANIM_GROUP_MOVE_BACK,
	ANIM_GROUP_MOVE_LEFT,
	ANIM_GROUP_MOVE_RIGHT,
	ANIM_GROUP_FAST_FORWARD,
	ANIM_GROUP_FAST_BACK,
	ANIM_GROUP_FAST_LEFT,
	ANIM_GROUP_FAST_RIGHT,
	ANIM_GROUP_DODGE_FORWARD,
	ANIM_GROUP_DODGE_BACK,
	ANIM_GROUP_DODGE_LEFT,
	ANIM_GROUP_DODGE_RIGHT,
	ANIM_GROUP_TURN_LEFT,
	ANIM_GROUP_TURN_RIGHT,
	ANIM_GROUP_AIM,
	ANIM_GROUP_AIM_UP,
	ANIM_GROUP_AIM_DOWN,
	ANIM_GROUP_AIM_IS,
	ANIM_GROUP_AIM_IS_UP,
	ANIM_GROUP_AIM_IS_DOWN,
	ANIM_GROUP_HOLSTER,
	ANIM_GROUP_EQUIP,
	ANIM_GROUP_UNEQUIP,
	ANIM_GROUP_ATTACK_LEFT,
	ANIM_GROUP_ATTACK_LEFT_UP,
	ANIM_GROUP_ATTACK_LEFT_DOWN,
	ANIM_GROUP_ATTACK_LEFT_IS,
	ANIM_GROUP_ATTACK_LEFT_IS_UP,
	ANIM_GROUP_ATTACK_LEFT_IS_DOWN,
	ANIM_GROUP_ATTACK_RIGHT,
	ANIM_GROUP_ATTACK_RIGHT_UP,
	ANIM_GROUP_ATTACK_RIGHT_DOWN,
	ANIM_GROUP_ATTACK_RIGHT_IS,
	ANIM_GROUP_ATTACK_RIGHT_IS_UP,
	ANIM_GROUP_ATTACK_RIGHT_IS_DOWN,
	ANIM_GROUP_ATTACK_3,
	ANIM_GROUP_ATTACK_3_UP,
	ANIM_GROUP_ATTACK_3_DOWN,
	ANIM_GROUP_ATTACK_3_IS,
	ANIM_GROUP_ATTACK_3_IS_UP,
	ANIM_GROUP_ATTACK_3_IS_DOWN,
	ANIM_GROUP_ATTACK_4,
	ANIM_GROUP_ATTACK_4_UP,
	ANIM_GROUP_ATTACK_4_DOWN,
	ANIM_GROUP_ATTACK_4_IS,
	ANIM_GROUP_ATTACK_4_IS_UP,
	ANIM_GROUP_ATTACK_4_IS_DOWN,
	ANIM_GROUP_ATTACK_5,
	ANIM_GROUP_ATTACK_5_UP,
	ANIM_GROUP_ATTACK_5_DOWN,
	ANIM_GROUP_ATTACK_5_IS,
	ANIM_GROUP_ATTACK_5_IS_UP,
	ANIM_GROUP_ATTACK_5_IS_DOWN,
	ANIM_GROUP_ATTACK_6,
	ANIM_GROUP_ATTACK_6_UP,
	ANIM_GROUP_ATTACK_6_DOWN,
	ANIM_GROUP_ATTACK_6_IS,
	ANIM_GROUP_ATTACK_6_IS_UP,
	ANIM_GROUP_ATTACK_6_IS_DOWN,
	ANIM_GROUP_ATTACK_7,
	ANIM_GROUP_ATTACK_7_UP,
	ANIM_GROUP_ATTACK_7_DOWN,
	ANIM_GROUP_ATTACK_7_IS,
	ANIM_GROUP_ATTACK_7_IS_UP,
	ANIM_GROUP_ATTACK_7_IS_DOWN,
	ANIM_GROUP_ATTACK_8,
	ANIM_GROUP_ATTACK_8_UP,
	ANIM_GROUP_ATTACK_8_DOWN,
	ANIM_GROUP_ATTACK_8_IS,
	ANIM_GROUP_ATTACK_8_IS_UP,
	ANIM_GROUP_ATTACK_8_IS_DOWN,
	ANIM_GROUP_ATTACK_LOOP,
	ANIM_GROUP_ATTACK_LOOP_UP,
	ANIM_GROUP_ATTACK_LOOP_DOWN,
	ANIM_GROUP_ATTACK_LOOP_IS,
	ANIM_GROUP_ATTACK_LOOP_IS_UP,
	ANIM_GROUP_ATTACK_LOOP_IS_DOWN,
	ANIM_GROUP_ATTACK_SPIN,
	ANIM_GROUP_ATTACK_SPIN_UP,
	ANIM_GROUP_ATTACK_SPIN_DOWN,
	ANIM_GROUP_ATTACK_SPIN_IS,
	ANIM_GROUP_ATTACK_SPIN_IS_UP,
	ANIM_GROUP_ATTACK_SPIN_IS_DOWN,
	ANIM_GROUP_ATTACK_SPIN_2,
	ANIM_GROUP_ATTACK_SPIN_2_UP,
	ANIM_GROUP_ATTACK_SPIN_2_DOWN,
	ANIM_GROUP_ATTACK_SPIN_2_IS,
	ANIM_GROUP_ATTACK_SPIN_2_IS_UP,
	ANIM_GROUP_ATTACK_SPIN_2_IS_DOWN,
	ANIM_GROUP_ATTACK_POWER,
	ANIM_GROUP_ATTACK_FORWARD_POWER,
	ANIM_GROUP_ATTACK_BACK_POWER,
	ANIM_GROUP_ATTACK_LEFT_POWER,
	ANIM_GROUP_ATTACK_RIGHT_POWER,
	ANIM_GROUP_ATTACK_CUSTOM_1_POWER,
	ANIM_GROUP_ATTACK_CUSTOM_2_POWER,
	ANIM_GROUP_ATTACK_CUSTOM_3_POWER,
	ANIM_GROUP_ATTACK_CUSTOM_4_POWER,
	ANIM_GROUP_ATTACK_CUSTOM_5_POWER,
	ANIM_GROUP_PLACE_MINE,
	ANIM_GROUP_PLACE_MINE_UP,
	ANIM_GROUP_PLACE_MINE_DOWN,
	ANIM_GROUP_PLACE_MINE_IS,
	ANIM_GROUP_PLACE_MINE_IS_UP,
	ANIM_GROUP_PLACE_MINE_IS_DOWN,
	ANIM_GROUP_PLACE_MINE_2,
	ANIM_GROUP_PLACE_MINE_2_UP,
	ANIM_GROUP_PLACE_MINE_2_DOWN,
	ANIM_GROUP_PLACE_MINE_2_IS,
	ANIM_GROUP_PLACE_MINE_2_IS_UP,
	ANIM_GROUP_PLACE_MINE_2_IS_DOWN,
	ANIM_GROUP_ATTACK_THROW,
	ANIM_GROUP_ATTACK_THROW_UP,
	ANIM_GROUP_ATTACK_THROW_DOWN,
	ANIM_GROUP_ATTACK_THROW_IS,
	ANIM_GROUP_ATTACK_THROW_IS_UP,
	ANIM_GROUP_ATTACK_THROW_IS_DOWN,
	ANIM_GROUP_ATTACK_THROW_2,
	ANIM_GROUP_ATTACK_THROW_2_UP,
	ANIM_GROUP_ATTACK_THROW_2_DOWN,
	ANIM_GROUP_ATTACK_THROW_2_IS,
	ANIM_GROUP_ATTACK_THROW_2_IS_UP,
	ANIM_GROUP_ATTACK_THROW_2_IS_DOWN,
	ANIM_GROUP_ATTACK_THROW_3,
	ANIM_GROUP_ATTACK_THROW_3_UP,
	ANIM_GROUP_ATTACK_THROW_3_DOWN,
	ANIM_GROUP_ATTACK_THROW_3_IS,
	ANIM_GROUP_ATTACK_THROW_3_IS_UP,
	ANIM_GROUP_ATTACK_THROW_3_IS_DOWN,
	ANIM_GROUP_ATTACK_THROW_4,
	ANIM_GROUP_ATTACK_THROW_4_UP,
	ANIM_GROUP_ATTACK_THROW_4_DOWN,
	ANIM_GROUP_ATTACK_THROW_4_IS,
	ANIM_GROUP_ATTACK_THROW_4_IS_UP,
	ANIM_GROUP_ATTACK_THROW_4_IS_DOWN,
	ANIM_GROUP_ATTACK_THROW_5,
	ANIM_GROUP_ATTACK_THROW_5_UP,
	ANIM_GROUP_ATTACK_THROW_5_DOWN,
	ANIM_GROUP_ATTACK_THROW_5_IS,
	ANIM_GROUP_ATTACK_THROW_5_IS_UP,
	ANIM_GROUP_ATTACK_THROW_5_IS_DOWN,
	ANIM_GROUP_ATTACK_9,
	ANIM_GROUP_ATTACK_9_UP,
	ANIM_GROUP_ATTACK_9_DOWN,
	ANIM_GROUP_ATTACK_9_IS,
	ANIM_GROUP_ATTACK_9_IS_UP,
	ANIM_GROUP_ATTACK_9_IS_DOWN,
	ANIM_GROUP_ATTACK_THROW_6,
	ANIM_GROUP_ATTACK_THROW_6_UP,
	ANIM_GROUP_ATTACK_THROW_6_DOWN,
	ANIM_GROUP_ATTACK_THROW_6_IS,
	ANIM_GROUP_ATTACK_THROW_6_IS_UP,
	ANIM_GROUP_ATTACK_THROW_6_IS_DOWN,
	ANIM_GROUP_ATTACK_THROW_7,
	ANIM_GROUP_ATTACK_THROW_7_UP,
	ANIM_GROUP_ATTACK_THROW_7_DOWN,
	ANIM_GROUP_ATTACK_THROW_7_IS,
	ANIM_GROUP_ATTACK_THROW_7_IS_UP,
	ANIM_GROUP_ATTACK_THROW_7_IS_DOWN,
	ANIM_GROUP_ATTACK_THROW_8,
	ANIM_GROUP_ATTACK_THROW_8_UP,
	ANIM_GROUP_ATTACK_THROW_8_DOWN,
	ANIM_GROUP_ATTACK_THROW_8_IS,
	ANIM_GROUP_ATTACK_THROW_8_IS_UP,
	ANIM_GROUP_ATTACK_THROW_8_IS_DOWN,
	ANIM_GROUP_COUNTER,
	ANIM_GROUP_STOMP,
	ANIM_GROUP_BLOCK_IDLE,
	ANIM_GROUP_BLOCK_HIT,
	ANIM_GROUP_RECOIL,
	ANIM_GROUP_RELOAD_W_START,
	ANIM_GROUP_RELOAD_X_START,
	ANIM_GROUP_RELOAD_Y_START,
	ANIM_GROUP_RELOAD_Z_START,
	ANIM_GROUP_RELOAD_A,
	ANIM_GROUP_RELOAD_B,
	ANIM_GROUP_RELOAD_C,
	ANIM_GROUP_RELOAD_D,
	ANIM_GROUP_RELOAD_E,
	ANIM_GROUP_RELOAD_F,
	ANIM_GROUP_RELOAD_G,
	ANIM_GROUP_RELOAD_H,
	ANIM_GROUP_RELOAD_I,
	ANIM_GROUP_RELOAD_J,
	ANIM_GROUP_RELOAD_K,
	ANIM_GROUP_RELOAD_L,
	ANIM_GROUP_RELOAD_M,
	ANIM_GROUP_RELOAD_N,
	ANIM_GROUP_RELOAD_O,
	ANIM_GROUP_RELOAD_P,
	ANIM_GROUP_RELOAD_Q,
	ANIM_GROUP_RELOAD_R,
	ANIM_GROUP_RELOAD_S,
	ANIM_GROUP_RELOAD_W,
	ANIM_GROUP_RELOAD_X,
	ANIM_GROUP_RELOAD_Y,
	ANIM_GROUP_RELOAD_Z,
	ANIM_GROUP_JAM_A,
	ANIM_GROUP_JAM_B,
	ANIM_GROUP_JAM_C,
	ANIM_GROUP_JAM_D,
	ANIM_GROUP_JAM_E,
	ANIM_GROUP_JAM_F,
	ANIM_GROUP_JAM_G,
	ANIM_GROUP_JAM_H,
	ANIM_GROUP_JAM_I,
	ANIM_GROUP_JAM_J,
	ANIM_GROUP_JAM_K,
	ANIM_GROUP_JAM_L,
	ANIM_GROUP_JAM_M,
	ANIM_GROUP_JAM_N,
	ANIM_GROUP_JAM_O,
	ANIM_GROUP_JAM_P,
	ANIM_GROUP_JAM_Q,
	ANIM_GROUP_JAM_R,
	ANIM_GROUP_JAM_S,
	ANIM_GROUP_JAM_W,
	ANIM_GROUP_JAM_X,
	ANIM_GROUP_JAM_Y,
	ANIM_GROUP_JAM_Z,
	ANIM_GROUP_STAGGER,
	ANIM_GROUP_DEATH,
	ANIM_GROUP_TALKING,
	ANIM_GROUP_PIPBOY,
	ANIM_GROUP_JUMP_START,
	ANIM_GROUP_JUMP_LOOP,
	ANIM_GROUP_JUMP_LAND,
	ANIM_GROUP_HAND_GRIP_1,
	ANIM_GROUP_HAND_GRIP_2,
	ANIM_GROUP_HAND_GRIP_3,
	ANIM_GROUP_HAND_GRIP_4,
	ANIM_GROUP_HAND_GRIP_5,
	ANIM_GROUP_HAND_GRIP_6,
	ANIM_GROUP_JUMP_LOOP_FORWARD,
	ANIM_GROUP_JUMP_LOOP_BACKWARD,
	ANIM_GROUP_JUMP_LOOP_LEFT,
	ANIM_GROUP_JUMP_LOOP_RIGHT,
	ANIM_GROUP_PIPBOY_CHILD,
	ANIM_GROUP_JUMP_LAND_FORWARD,
	ANIM_GROUP_JUMP_LAND_BACKWARD,
	ANIM_GROUP_JUMP_LAND_LEFT,
	ANIM_GROUP_JUMP_LAND_RIGHT,

	ANIM_GROUP_COUNT,
};

enum ANIM_GROUP_ACTION {
	AGA_NONE					= -1,

	AGA_START					= 0,
	AGA_STOP					= 1,

	AGA_LOOP_START				= 0,
	AGA_LOOP_STOP				= 1,

	AGA_SPECIAL_IDLE_START		= 0,
	AGA_SPECIAL_IDLE_LOOP_START	= 1,
	AGA_SPECIAL_IDLE_LOOP_STOP	= 2,
	AGA_SPECIAL_IDLE_STOP		= 3,

	AGA_LOOPING_RELOAD_START	= 0,
	AGA_LOOPING_RELOAD_LOOP		= 1,
	AGA_LOOPING_RELOAD_STOP		= 2,

	AGA_ATTACK_START			= 0,
	AGA_ATTACK_HIT				= 1,
	AGA_ATTACK_EJECT			= 2,
	AGA_ATTACK_POWER_STOP		= 2,
	AGA_ATTACK_SWITCH			= 3,
	AGA_ATTACK_STOP				= 4,

	AGA_ATTACK_MINE_START		= 0,
	AGA_ATTACK_MINE_RELEASE		= 1,
	AGA_ATTACK_MINE_ATTACH		= 2,
	AGA_ATTACK_MINE_STOP		= 3,

	AGA_ATTACK_SPIN_START		= 0,
	AGA_ATTACK_SPIN_FIRE		= 1,
	AGA_ATTACK_SPIN_LOOP		= 2,
	AGA_ATTACK_SPIN_STOP		= 3,

	AGA_ATTACK_THROW_START		= 0,
	AGA_ATTACK_THROW_HOLD		= 1,
	AGA_ATTACK_THROW_RELEASE	= 2,
	AGA_ATTACK_THROW_ATTACH		= 3,
	AGA_ATTACK_THROW_STOP		= 4,
	ANIM_GROUP_ACTION_COUNT		= 5,

	AGA_BLOCK_START				= 0,
	AGA_BLOCK_ATTACK			= 1,
	AGA_BLOCK_STOP				= 2,

	AGA_EQUIP_START				= 0,
	AGA_EQUIP_ATTACH			= 1,
	AGA_EQUIP_STOP				= 2,

	AGA_UNEQUIP_START			= 0,
	AGA_UNEQUIP_DETACH			= 1,
	AGA_UNEQUIP_STOP			= 2,

	AGA_CAST_START				= 0,
	AGA_CAST_HIT				= 1,
	AGA_CAST_STOP				= 2,
};

struct _AnimationGroupActionType {
	enum Type : uint32_t {
		START_STOP,
		LOOP,
		SPECIAL_IDLE,
		EQUIP,
		UNEQUIP,
		ATTACK,
		ATTACK_POWER,
		ATTACK_THROW,
		ATTACK_THROW_ATTACH,
		ATTACK_SPIN,
		COUNT
	};
};
using ANIM_GROUP_ACTION_TYPE = _AnimationGroupActionType::Type;

struct _AnimationGroupSection {
	enum Section : int32_t {
		NONE			= -1,
		IDLE			= 0,
		MOVEMENT		= 1,
		LEFT_ARM		= 2,
		AGS_TALKING		= 3,
		WEAPON			= 4,
		WEAPON_UP		= 5,
		WEAPON_DOWN		= 6,
		SPECIAL_IDLE	= 7,
		COUNT			= 8,
		WHOLE_BODY		= 20,
		UPPER_BODY		= 21,
		TOTAL_COUNT,
		SKIP_ALL_BUT_SPECIAL_IDLE = 23,
	};
};
using ANIM_GROUP_SECTION = _AnimationGroupSection::Section;

struct _AnimationActionFlags {
	enum Action : uint32_t {
		NORMAL			= 0,
		IMMEDIATE_START = 1,
		IMMEDIATE_LOOP	= 2,
	};
};
using ANIM_ACTION_FLAGS = _AnimationActionFlags::Action;

struct _AnimationIdleState {
	enum State : uint32_t {
		NONE			= 0,
		QUEUED			= 1,
		LOADED			= 2,
		PLAYING			= 3,
		DONE_PLAYING	= 4,
	};
};
using ANIM_IDLE_STATE = _AnimationIdleState::State;

struct _AnimationIdlePlayType {
	enum Type : uint32_t {
		REPLACE			= 0,
		QUEUE			= 1,
		AUTO			= 2,
		AUTO_EXCLUSIVE	= 3,
	};
};
using ANIM_IDLE_PLAY_TYPE = _AnimationIdlePlayType::Type;

#pragma endregion

enum CONFIDENCE : uint8_t {
	CONFIDENCE_COWARDLY		= 0,
	CONFIDENCE_CAUTIOUS		= 1,
	CONFIDENCE_AVERAGE		= 2,
	CONFIDENCE_BRAVE		= 3,
	CONFIDENCE_FOOLHARDY	= 4,
	CONFIDENCE_COUNT,
};


#pragma region Weapons

enum WEAPON_TYPE {
	WEAPON_TYPE_HAND_TO_HAND_MELEE		= 0,
	WEAPON_TYPE_ONE_HAND_MELEE			= 1,
	WEAPON_TYPE_TWO_HAND_MELEE			= 2,
	WEAPON_TYPE_ONE_HAND_PISTOL			= 3,
	WEAPON_TYPE_ONE_HAND_PISTOL_ENERGY	= 4,
	WEAPON_TYPE_TWO_HAND_RIFLE			= 5,
	WEAPON_TYPE_TWO_HAND_AUTOMATIC		= 6,
	WEAPON_TYPE_TWO_HAND_RIFLE_ENERGY	= 7,
	WEAPON_TYPE_TWO_HAND_HANDLE			= 8,
	WEAPON_TYPE_TWO_HAND_LAUNCHER		= 9,
	WEAPON_TYPE_ONE_HAND_GRENADE		= 10,
	WEAPON_TYPE_ONE_HAND_MINE			= 11,
	WEAPON_TYPE_ONE_HAND_LUNCHBOX_MINE	= 12,
	WEAPON_TYPE_ONE_HAND_THROWN			= 13,
	WEAPON_TYPE_COUNT,
};

enum COMBAT_WEAPON_TYPE {
	COMBAT_WEAPON_TYPE_RANGED_EXPLOSIVE = 0,
	COMBAT_WEAPON_TYPE_RANGED			= 1,
	COMBAT_WEAPON_TYPE_MELEE			= 2,
	COMBAT_WEAPON_TYPE_GRENADE			= 3,
	COMBAT_WEAPON_TYPE_MINE				= 4,
	COMBAT_WEAPON_TYPE_THROWN			= 5,
	COMBAT_WEAPON_TYPE_NONE				= 6,
	COMBAT_WEAPON_TYPE_INVALID			= 7,

	COMBAT_WEAPON_TYPE_COUNT = COMBAT_WEAPON_TYPE_NONE,
};

enum WEAPON_SOUND {
	WEAPON_SOUND_SHOOT_3D = 0,
	WEAPON_SOUND_SHOOT_2D,
	WEAPON_SOUND_SHOOT_3D_LOOPING,
	WEAPON_SOUND_NO_AMMO,
	WEAPON_SOUND_SWING = WEAPON_SOUND_NO_AMMO,
	WEAPON_SOUND_BLOCK,
	WEAPON_SOUND_IDLE,
	WEAPON_SOUND_EQUIP,
	WEAPON_SOUND_UNEQUIP
};

enum ATTACK_ANIMATION {
	ATTACK_ANIMATION_DEFAULT		= 255,
	ATTACK_ANIMATION_ATTACK_3		= 38,
	ATTACK_ANIMATION_ATTACK_4		= 44,
	ATTACK_ANIMATION_ATTACK_5		= 50,
	ATTACK_ANIMATION_ATTACK_6		= 56,
	ATTACK_ANIMATION_ATTACK_7		= 62,
	ATTACK_ANIMATION_ATTACK_8		= 68,
	ATTACK_ANIMATION_ATTACK_9		= 144,
	ATTACK_ANIMATION_ATTACK_LEFT	= 26,
	ATTACK_ANIMATION_ATTACK_LOOP	= 74,
	ATTACK_ANIMATION_ATTACK_RIGHT	= 32,
	ATTACK_ANIMATION_ATTACK_SPIN	= 80,
	ATTACK_ANIMATION_ATTACK_SPIN_2	= 86,
	ATTACK_ANIMATION_ATTACK_THROW	= 114,
	ATTACK_ANIMATION_ATTACK_THROW_2 = 120,
	ATTACK_ANIMATION_ATTACK_THROW_3 = 126,
	ATTACK_ANIMATION_ATTACK_THROW_4 = 132,
	ATTACK_ANIMATION_ATTACK_THROW_5 = 138,
	ATTACK_ANIMATION_ATTACK_THROW_6 = 150,
	ATTACK_ANIMATION_ATTACK_THROW_7 = 156,
	ATTACK_ANIMATION_ATTACK_THROW_8 = 162,
	ATTACK_ANIMATION_PLACE_MINE		= 102,
	ATTACK_ANIMATION_PLACE_MINE_2	= 108,
	ATTACK_ANIMATION_COUNT			= 23,
};

enum RELOAD_ANIM {
	RELOAD_ANIM_A = 0,
	RELOAD_ANIM_B,
	RELOAD_ANIM_C,
	RELOAD_ANIM_D,
	RELOAD_ANIM_E,
	RELOAD_ANIM_F,
	RELOAD_ANIM_G,
	RELOAD_ANIM_H,
	RELOAD_ANIM_I,
	RELOAD_ANIM_J,
	RELOAD_ANIM_K,
	RELOAD_ANIM_L,
	RELOAD_ANIM_M,
	RELOAD_ANIM_N,
	RELOAD_ANIM_O,
	RELOAD_ANIM_P,
	RELOAD_ANIM_Q,
	RELOAD_ANIM_R,
	RELOAD_ANIM_S,
	RELOAD_ANIM_W,
	RELOAD_ANIM_X,
	RELOAD_ANIM_Y,
	RELOAD_ANIM_Z,
	RELOAD_ANIM_COUNT,
};
static_assert(RELOAD_ANIM_COUNT == 23);

enum WEAPON_RUMBLE_PATTERN {
	WEAPON_RUMBLE_PATTERN_CONSTANT = 0,
	WEAPON_RUMBLE_PATTERN_SQUARE,
	WEAPON_RUMBLE_PATTERN_TRIANGLE,
	WEAPON_RUMBLE_PATTERN_SAWTOOTH
};

#pragma endregion

#pragma region Combat

enum COMBAT_LOW_STATE : uint32_t {
	COMBAT_LOW_STATE_NONE			= 0,
	COMBAT_LOW_STATE_ATTACKING		= 1,
	COMBAT_LOW_STATE_PURSUING		= 2,
	COMBAT_LOW_STATE_INVESTIGATING	= 3,
	COMBAT_LOW_STATE_SEARCHING		= 4,
	COMBAT_LOW_STATE_FLEEING		= 5,
	COMBAT_LOW_STATE_COUNT			= 6,
};

enum COMBAT_VARIABLE : uint32_t {
	TARGET_LOCATION				= 0,
	NEAR_TARGET_LOCATION		= 1,
	COVER_LOCATION				= 2,
	DODGE_LOCATION				= 3,
	FLANK_LOCATION				= 4,
	FALLBACK_LOCATION			= 5,
	ADVANCE_LOCATION			= 6,
	DESTINATION_LOCATION		= 7,
	GUARD_LOCATION				= 8,
	CLUSTER_LOCATION			= 9,
	HIDE_LOCATION				= 10,
	GRENADE_LOCATION			= 11,
	FLEE_LOCATION				= 12,
	LOS_LOCATION				= 13,
	SAFE_LOCATION				= 14,
	INVESTIGATE_LOCATION		= 15,
	COMBAT_AREA_LOCATION		= 16,
	COMBAT_LOCATION_COUNT		= 17,

	COMBAT_ITEM_RESTORE			= 17,
	COMBAT_ITEM_BUFF			= 18,
	COMBAT_ITEM_TARGET_OBJECT	= 19,
	COMBAT_ITEM_AMMO			= 20,
	COMBAT_ITEM_WEAPON			= 21,
	COMBAT_ITEM_END				= 22,
	COMBAT_ITEM_COUNT			= 5,

	COMBAT_ITEM_START			= COMBAT_ITEM_RESTORE,
	COMBAT_ITEM_USABLE_END		= COMBAT_ITEM_TARGET_OBJECT,
	COMBAT_ITEM_USABLE_COUNT	= 2,

	TOTAL_COMBAT_LOCATION_COUNT	= 22,

	SPECIFIED_VARIABLE_START	= 0xFFFF0016,
	ACTIVATE_COMBAT_ITEM		= 0xFFFF0016,
	USE_COMBAT_ITEM				= 0xFFFF0017,
	EQUIPPED_WEAPON_TYPE		= 0xFFFF0018,
	SPECIFIED_VARIABLE_END		= 0xFFFF0019,
	SPECIFIED_VARIABLE_COUNT	= 3,
	COMBAT_VARIABLE_COUNT		= 25,

	ANY_LOCATION				= 0xFFFFFFFF,
	ANY_COMBAT_ITEM				= 0xFFFFFFFF,
	ANY_WEAPON_TYPE				= 0xFFFFFFFF,
	ANY_VALUE					= 0xFFFFFFFF,
};

enum COMBAT_MOVE_MODE : uint32_t {
	COMBAT_MOVE_MODE_WALK		= 0,
	COMBAT_MOVE_MODE_FAST_WALK	= 1,
	COMBAT_MOVE_MODE_SNEAK		= 2,
	COMBAT_MOVE_MODE_RUN		= 3,
	COMBAT_MOVE_MODE_SLOW_RUN	= 4,
	COMBAT_MOVE_MODE_COUNT		= 5,
};

enum COMBAT_LOCATION_FLAGS : uint32_t {
	COMBAT_LOCATION_USE_EVADE	= 1,
	COMBAT_LOCATION_HARD_RADIUS = 2,
};

enum COMBAT_WORLD_STATE : uint32_t {
	COMBAT_WORLD_STATE_TARGET_DEAD					= 0,
	COMBAT_WORLD_STATE_AT_LOCATION					= 1, // -> COMBAT_LOCATION_TYPE
	COMBAT_WORLD_STATE_NOT_AT_LOCATION				= 2, // -> COMBAT_LOCATION_TYPE
	COMBAT_WORLD_STATE_TARGET_LOST					= 3,
	COMBAT_WORLD_STATE_TARGET_DETECTED				= 4,
	COMBAT_WORLD_STATE_TARGET_360_LOS				= 5,
	COMBAT_WORLD_STATE_TARGET_BLOCKED				= 6,
	COMBAT_WORLD_STATE_TARGET_SPACE_DIFFERENT		= 7,
	COMBAT_WORLD_STATE_EXPLOSIVE_PROJECTILE_BLOCKED = 8,
	COMBAT_WORLD_STATE_TARGET_FLUSHED				= 9,
	COMBAT_WORLD_STATE_WEAPON_DRAWN					= 10, // -> COMBAT_WEAPON_TYPE
	COMBAT_WORLD_STATE_WEAPON_TYPE_EQUIPPED			= 11, // -> COMBAT_WEAPON_TYPE
	COMBAT_WORLD_STATE_HAS_WEAPON_TYPE				= 12, // -> COMBAT_WEAPON_TYPE
	COMBAT_WORLD_STATE_HAS_COMBAT_ITEM				= 13, // -> COMBAT_LOCATION_TYPE
	COMBAT_WORLD_STATE_THREATENED					= 14,
	COMBAT_WORLD_STATE_WANTS_TO_FLEE				= 15,
	COMBAT_WORLD_STATE_USED_COMBAT_ITEM				= 16,
	COMBAT_WORLD_STATE_HIDING						= 17,
	COMBAT_WORLD_STATE_EXECUTION_FLAGS				= 18, // -> COMBAT_PERMISSIONS
	COMBAT_WORLD_STATE_GROUP_STRATEGY_ASSIGNMENT	= 19,
	COMBAT_WORLD_STATE_COUNT,
};

enum COMBAT_EXECUTION_FLAGS : uint32_t {
	COMBAT_PERMISSION_USE_COVER				= 0,
	COMBAT_PERMISSION_CAN_USE_COVER			= 1,
	COMBAT_PERMISSION_LOW_COUNT				= 2,

	COMBAT_PERMISSION_AVOID_THREATS			= 8,
	COMBAT_PERMISSION_HIGH_START			= COMBAT_PERMISSION_AVOID_THREATS,
	COMBAT_PERMISSION_HIGH_END				= 9,
	COMBAT_PERMISSION_HIGH_COUNT			= 1,

	COMBAT_EXECUTION_FLAG_GROUP_SEARCHING	= 16,
	COMBAT_EXECUTION_FLAG_CAN_MOVE			= 17,
	COMBAT_EXECUTION_FLAG_CAN_MELEE_TARGET	= 18,
	COMBAT_EXECUTION_FLAG_START				= COMBAT_EXECUTION_FLAG_GROUP_SEARCHING,
	COMBAT_EXECUTION_FLAG_COUNT				= 19,

};

enum COMBAT_ITEM_TYPE {
	COMBAT_ITEM_TYPE_RESTORE	= 0,
	COMBAT_ITEM_TYPE_BUFF		= 1,
	COMBAT_ITEM_TYPE_COUNT,
};

enum LOCATION_TARGET_TYPE : uint8_t {
	LOCATION_TARGET_TYPE_DESTINATION,
	LOCATION_TARGET_TYPE_GUARD,
	LOCATION_TARGET_TYPE_CLUSTER,
	LOCATION_TARGET_TYPE_COMBAT_AREA,
};

enum COMBAT_PROCEDURE_TYPE {
	COMBAT_PROCEDURE_ATTACK_RANGED		= 0,
	COMBAT_PROCEDURE_ATTACK_MELEE		= 1,
	COMBAT_PROCEDURE_ATTACK_GRENADE		= 2,
	COMBAT_PROCEDURE_ATTACK_LOW			= 3,
	COMBAT_PROCEDURE_EVADE				= 4,
	COMBAT_PROCEDURE_SWITCH_WEAPON		= 5,
	COMBAT_PROCEDURE_MOVE				= 6,
	COMBAT_PROCEDURE_BE_IN_COVER		= 7,
	COMBAT_PROCEDURE_ACTIVATE_OBJECT	= 8,
	COMBAT_PROCEDURE_HIDE_FROM_TARGET	= 9,
	COMBAT_PROCEDURE_SEARCH				= 10,
	COMBAT_PROCEDURE_USE_COMBAT_ITEM	= 11,
	COMBAT_PROCEDURE_ENGAGE_TARGET		= 12,
};

enum COMBAT_ACTION_TYPE {
	COMBAT_ACTION_ATTACK_RANGED_EXPLOSIVE,
	COMBAT_ACTION_ATTACK_RANGED_EXPLOSIVE_COVER,
	COMBAT_ACTION_ATTACK_RANGED,
	COMBAT_ACTION_ATTACK_RANGED_COVER,
	COMBAT_ACTION_ATTACK_GRENADE,
	COMBAT_ACTION_ATTACK_GRENADE_FLUSH_TARGET,
	COMBAT_ACTION_ATTACK_GRENADE_COVER,
	COMBAT_ACTION_ATTACK_MELEE,
	COMBAT_ACTION_ATTACK_HAND_TO_HAND,
	COMBAT_ACTION_MOVE,
	COMBAT_ACTION_MOVE_SWITCH_TO_MELEE,
	COMBAT_ACTION_MOVE_ATTACK_RANGED,
	COMBAT_ACTION_MOVE_ATTACK_EXPLOSIVE,
	COMBAT_ACTION_MOVE_ATTACK_GRENADE,
	COMBAT_ACTION_DRAW_WEAPON,
	COMBAT_ACTION_SWITCH_WEAPON,
	COMBAT_ACTION_AVOID_THREAT,
	COMBAT_ACTION_SEARCH,
	COMBAT_ACTION_INVESTIGATE,
	COMBAT_ACTION_DODGE,
	COMBAT_ACTION_IGNORE_BLOCKED_TARGET,
	COMBAT_ACTION_FLEE,
	COMBAT_ACTION_ACTIVATE_COMBAT_ITEM,
	COMBAT_ACTION_USE_COMBAT_ITEM,
	COMBAT_ACTION_ACQUIRE_LOS,
	COMBAT_ACTION_HIDE,
	COMBAT_ACTION_APPROACH_TARGET,
};

enum COMBAT_GROUP_STRATEGY {
	COMBAT_GROUP_STRATEGY_FALLBACK	= 0,
	COMBAT_GROUP_STRATEGY_ADVANCE	= 1,
	COMBAT_GROUP_STRATEGY_FLANK		= 2,
	COMBAT_GROUP_STRATEGY_AMBUSH	= 3,
	COMBAT_GROUP_STRATEGY_COUNT		= 4,
};

#pragma endregion

enum DIALOGUE_TYPE {
	DT_TOPIC			= 0,
	DT_CONVERSATION		= 1,
	DT_COMBAT			= 2,
	DT_PERSUASION		= 3,
	DT_DETECTION		= 4,
	DT_SERVICE			= 5,
	DT_MISCELLANEOUS	= 6,
	DT_RADIO			= 7,
	DIALOGUE_TYPE_COUNT,
};

enum FACTION_RELATION : uint32_t {
	FACTION_RELATION_ENEMY		= 0,
	FACTION_RELATION_NEUTRAL	= 1,
	FACTION_RELATION_ALLY		= 2,
	FACTION_RELATION_FRIEND		= 3,
};

enum ACTOR_SEGMENT_INVIEW : uint32_t {
	ACTOR_SEGMENT_INVIEW_BOTTOM = 0,
	ACTOR_SEGMENT_INVIEW_MIDDLE = 1,
	ACTOR_SEGMENT_INVIEW_TOP	= 2,
	ACTOR_SEGMENT_INVIEW_NONE	= 3,
};

enum HavokMaterialType {
	BHK_MATERIAL_STONE				= 0,
	BHK_MATERIAL_CLOTH				= 1,
	BHK_MATERIAL_DIRT				= 2,
	BHK_MATERIAL_GLASS				= 3,
	BHK_MATERIAL_GRASS				= 4,
	BHK_MATERIAL_METAL				= 5,
	BHK_MATERIAL_ORGANIC			= 6,
	BHK_MATERIAL_SKIN				= 7,
	BHK_MATERIAL_WATER				= 8,
	BHK_MATERIAL_WOOD				= 9,
	BHK_MATERIAL_HEAVYSTONE			= 10,
	BHK_MATERIAL_HEAVYMETAL			= 11,
	BHK_MATERIAL_HEAVYWOOD			= 12,
	BHK_MATERIAL_CHAIN				= 13,
	BHK_MATERIAL_SNOW				= 14,
	BHK_MATERIAL_ELEVATOR			= 15,
	BHK_MATERIAL_HOLLOWMETAL		= 16,
	BHK_MATERIAL_SHEETMETAL			= 17,
	BHK_MATERIAL_SAND				= 18,
	BHK_MATERIAL_BROKENCONCRETE		= 19,
	BHK_MATERIAL_VEHICLEBODY		= 20,
	BHK_MATERIAL_VEHICLEPARTSOLID	= 21,
	BHK_MATERIAL_VEHICLEPARTHOLLOW	= 22,
	BHK_MATERIAL_BARREL				= 23,
	BHK_MATERIAL_BOTTLE				= 24,
	BHK_MATERIAL_SODACAN			= 25,
	BHK_MATERIAL_PISTOL				= 26,
	BHK_MATERIAL_RIFLE				= 27,
	BHK_MATERIAL_SHOPPINGCART		= 28,
	BHK_MATERIAL_LUNCHBOX			= 29,
	BHK_MATERIAL_BABYRATTLE			= 30,
	BHK_MATERIAL_RUBBERBALL			= 31,
	BHK_MATERIAL_CHAINLINK			= 32,
	BHK_MATERIAL_TILE				= 33,
	BHK_MATERIAL_CARPET				= 34,
	BHK_MATERIAL_TUMBLEWEED			= 35,
	BHK_MATERIAL_MAX,

	BHK_MATERIAL_FLAG_STAIRS		= 0x40,

	BHK_MATERIAL_MASK				= 0x1F,
	BHK_MATERIAL_MASK_FIXED			= 0x3F,
};

enum SoundMessageType : uint32_t {
	SM_PLAY						= 0x1,
	SM_UNPAUSE					= 0x2,
	SM_PAUSE					= 0x3,
	SM_STOP						= 0x4,
	SM_PLAY_AFTER				= 0x5,
	//							  0x6
	SM_MUTE						= 0x7,
	SM_UNMUTE					= 0x8,
	SM_FADE_OUT_TARGET			= 0x9, // What's the difference?
	SM_FADE_OUT					= 0xA, // What's the difference? Used by Fade Dialogue
	SM_FADE_IN_TARGET			= 0xB, // What's the difference?
	SM_FADE_IN					= 0xC, // What's the difference? Used by Fade Dialogue
	SM_FADE_DIALOGUE			= 0xD,
	SM_VOLUME_CHANGED			= 0xE,
	SM_SET_VOLUME				= 0x10,
	//							  0x11
	//							  0x12
	SM_SET_FREQUENCY			= 0x13,
	SM_SET_FREQUENCY_VARIANCE	= 0x14,
	//							  0x15
	//							  0x16
	//							  0x17
	SM_FADE_OUT_SELECTED		= 0x18,
	SM_FADE_IN_SELECTED			= 0x19,
	SM_STOP_SELECTED			= 0x1A, // Flags stuff in pPauseEntries. Stops/mutes sounds based on given flags. Doesn't apply to music/radio. AUDIOFLAG_UNKBIT22 is muted instead of stopped.
	SM_START_SELECTED			= 0x1B, // Reverts above
	SM_STOP_SUBMERGED_1C		= 0x1C, // Similar to 1A, but checks water submersion flags
	SM_START_SUBMERGED_1D		= 0x1D, // Reverts above
	SM_SET_POS					= 0x1E,
	SM_SET_BEAM_END				= 0x1F,
	//							  0x20
	SM_SET_STATIC_ATTENUATION	= 0x21,
	SM_SET_REVERB_ATTENUATION	= 0x22,
	SM_SET_MINMAX_DISTANCE		= 0x23,
	SM_SET_ATTENUATION_CURVE	= 0x24,
	SM_PRECACHE					= 0x25,
	SM_RELEASE					= 0x26,
	SM_REGISTER_MOVING_SOUND	= 0x27,
	SM_RELEASE_MOVING_SOUNDS	= 0x28,
	SM_STOP_MOVING_SOUNDS		= 0x29, // Filtered, per ref
	SM_RELEASE_SELECTED			= 0x2A, // Filtered
	//							  0x2B
	//							  0x2C
	SM_UNUSED_2D				= 0x2D,
	//							  0x2E
	//							  0x2F
	//							  0x30
	//							  0x31
	//							  0x32
	SM_CACHE					= 0x33,
	SM_STOP_AUDIO_THREAD		= 0x34,
	SM_SUSPEND_AUDIO_THREAD		= 0x35,
	//							  0x36
	SM_UPDATE_UNDERWATER		= 0x37,
	SM_SET_LISTENER_POS			= 0x38,
	SM_UNKNOWN_39				= 0x39, // Calls ProcessDataRequest if STATE_UNK_11 and STATE_UNK_8 (ProcessDataRequest is stubbed)
	SM_SET_COMPLETION_CALLBACK	= 0x3A,
	SM_SET_PLAY_CALLBACK		= 0x3B,
	SM_UNKNOWN_3C				= 0x3C, // if STATE_UNK_8, sets unk15C and AUDIOFLAG_UNKBIT24. Used by radio
	SM_UNKNOWN_3D				= 0x3D, // Undoes above. Unused
	SM_SET_START_END			= 0x3E,
	SM_SEEK_MUSIC				= 0x3F,
	SM_SET_1ST_PERSON_SOUND		= 0x40,
	SM_SET_PRIORITY				= 0x41,
	SM_SET_SPEED				= 0x42,
};

enum SCRIPT_COMPILER_NAME : uint32_t {
	DEFAULT_COMPILER		= 0,
	SYSTEM_WINDOW_COMPILER	= 1,
	DIALOGUE_COMPILER		= 2,
	COMPILER_NAME_COUNT,
};

struct _RayCastPathRequestType {
	enum Type : uint32_t {
		START	= 0,
		GOAL	= 1,
		NO_MESH = 2
	};
};
using RAYCAST_PATH_REQUEST_TYPE = _RayCastPathRequestType::Type;

struct _RayCastPathResult {
	enum Result : uint32_t {
		NONE	= 0,
		SUCCESS = 1,
		FAILED	= 2,
	};
};
using RAYCAST_PATH_RESULT = _RayCastPathResult::Result;

struct _ArchiveType {
	enum Type {
		ALL_		= UINT32_MAX,
		ALL			= UINT16_MAX,
		MESHES		= 0x1,
		TEXTURES	= 0x2,
		MENUS		= 0x4,
		SOUNDS		= 0x8,
		VOICES		= 0x10,
		SHADERS		= 0x20,
		TREES		= 0x40,
		FONTS		= 0x80,
		MISC		= 0x100,
		COUNT		= 9,
	};
};
using ARCHIVE_TYPE = _ArchiveType::Type;

struct _ArchiveTypeIndex {
	enum Index : uint32_t {
		MESHES		= 0,
		TEXTURES	= 1,
		MENUS		= 2,
		SOUNDS		= 3,
		VOICES		= 4,
		SHADERS		= 5,
		TREES		= 6,
		FONTS		= 7,
		MISC		= 8,
		COUNT		= 9,
	};
};
using ARCHIVE_TYPE_INDEX = _ArchiveTypeIndex::Index;

struct _BodyPartType {
	enum Type : int32_t {
		NONE = -1,
		TORSO,
		HEAD_1,
		HEAD_2,
		LEFT_ARM_1,
		LEFT_ARM_2,
		RIGHT_ARM_1,
		RIGHT_ARM_2,
		LEFT_LEG_1,
		LEFT_LEG_2,
		LEFT_LEG_3,
		RIGHT_LEG_1,
		RIGHT_LEG_2,
		RIGHT_LEG_3,
		BRAIN,
		WEAPON,
		COUNT,
	};
};
using BODY_PART_TYPE = _BodyPartType::Type;

struct _DetectionLevel {
	enum Level : uint32_t {
		LOST	= 0,
		UNSEEN	= 1,
		NOTICED	= 2,
		SEEN	= 3,
		COUNT	= 4,
	};
};
using DETECTION_LEVEL = _DetectionLevel::Level;

struct _ActorType {
	enum Type {
		CREATURE	= 0,
		CHARACTER	= 1,
		PLAYER		= 2,
	};
};
using ACTOR_TYPE = _ActorType::Type;

struct _CreatureType {
	enum Type {
		ANIMAL			= 0,
		MUTATED_ANIMAL	= 1,
		MUTATED_INSECT	= 2,
		ABOMINATION		= 3,
		SUPER_MUTANT	= 4,
		FERAL_GHOUL		= 5,
		ROBOT			= 6,
		GIANT			= 7
	};
};
using CREATURE_TYPE = _CreatureType::Type;