[MAIN]
; Stops NPCs from running away from you while you're in [CAUTION] state, but there are no enemies around.
bFixFleeing = 0

; Fixes an integer overflow bug in item stacks. When you drop a stack of more than 32000 items from the inventory, the item count will overflow
; into negatives because the value is stored in a signed 16-bit integer. This fix works around it by dropping multiple stacks of 10000 items instead.
bFixItemStackCount = 1

; Fixes a combat style bug which caused NPCs to ignore line of sight/viewing angle checks and shoot "through their backs" at the player instead of rotating to face them.
; This worked correctly in Falout 3 and became broken in New Vegas.
; Disable if you prefer vanilla behavior.
bFixNPCShootingAngle = 0

; Disables hardcoded cooldown between creating muzzle flashes when firing weapons.
bNoMuzzleFlashCooldown = 0

; Resets 3rd person camera position after using vanity mode camera.
bReset3rdPersonCamera = 0

; Fixes voice lines for actor's death being cut off halfway through.
bFixDeathVoicelines = 0

; Tiny patch to remove the player character's face having a pained expression "randomly". By request.
bRemovePlayerPainExpression = 0

; Applies various fixes to the JIP LN NVSE plugin, version 57.30 only.
bJIPFixes = 1


; Section to make JIP's existing fixes toggleable
[JIP]
; From Jazz:
; "Code-level fix for the 'Modify Positive Chem Duration' perk entry point to only effect 'Chems' (instead of all ingestibles) as was intended and as it did in Fallout 3."
bFixPositiveChemDuration=1