#pragma once
// Get/Set/Boolean functions for various form types
#include "fn_common.h"
DEFINE_COMMAND_PLUGIN(GetBaseEffectAV, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(GetBaseEffectArchetype, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(GetInteriorLightingTraitNumeric, , false, kParams_OneForm_OneInt);
DEFINE_COMMAND_PLUGIN(SetInteriorLightingTraitNumeric, , false, kParams_OneForm_OneInt_OneFloat);
DEFINE_COMMAND_PLUGIN(GetIMODAnimatable, , false, kParams_OneIMOD);
DEFINE_COMMAND_PLUGIN(SetIMODAnimatable, , false, kParams_OneIMOD_OneInt);
DEFINE_COMMAND_PLUGIN(SetWeapon1stPersonModel, , false, kParams_OneForm_OneInt_OneOptionalForm);
DEFINE_COMMAND_PLUGIN(GetWeapon1stPersonModel, , false, kParams_OneForm_OneInt);
DEFINE_COMMAND_PLUGIN(GetMusicTypePath, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(GetMusicTypeDB, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(SetMusicTypeDB, , false, kParams_OneForm_OneFloat);
DEFINE_COMMAND_PLUGIN(SetMusicTypePath, , false, kParams_OneForm_OneString);
DEFINE_COMMAND_PLUGIN(SetExplosionSound, , false, kParams_OneForm_OneInt_OneForm);
DEFINE_COMMAND_PLUGIN(SetProjectileSound, , false, kParams_OneForm_OneInt_OneForm);
DEFINE_COMMAND_PLUGIN(GetWeaponWorldModelPath, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(SetWeaponWorldModelPath, , false, kParams_OneForm_OneString);
DEFINE_CMD_COND_PLUGIN(GetLifeState, , true, nullptr);
DEFINE_COMMAND_PLUGIN(GetRaceFlag, , false, kParams_OneForm_OneInt);
DEFINE_COMMAND_PLUGIN(SetRaceFlag, , false, kParams_OneForm_TwoInts);
DEFINE_COMMAND_PLUGIN(GetContainerSound, , false, kParams_OneForm_OneInt);
DEFINE_COMMAND_PLUGIN(SetContainerSound, , false, kParams_OneForm_OneInt_OneForm);
DEFINE_COMMAND_PLUGIN(GetCreatureCombatSkill, , false, kParams_OneOptionalActorBase);
DEFINE_COMMAND_PLUGIN(GetFacegenModelFlag, , false, kParams_OneForm_TwoInts);
DEFINE_COMMAND_PLUGIN(SetFacegenModelFlag, , false, kParams_OneForm_ThreeInts);
DEFINE_COMMAND_PLUGIN(GetRaceBodyModelPath, , false, kParams_OneForm_TwoInts);
DEFINE_COMMAND_PLUGIN(SetEquipType, , false, kParams_OneForm_OneInt);
DEFINE_COMMAND_PLUGIN(GetFactionMembers, , false, kParams_OneForm_OneOptionalInt);
DEFINE_COMMAND_PLUGIN(GetRaceHeadModelPath, , false, kParams_OneForm_TwoInts);
DEFINE_COMMAND_PLUGIN(GetCalculatedWeaponDPS, , false, kParams_OneOptionalObjectID);
DEFINE_COMMAND_PLUGIN(IsCellVisited, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(IsCellExpired, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(GetBufferedCellsAlt, , false, kParams_OneInt);
DEFINE_COMMAND_ALT_PLUGIN(GetActorValueModifierAlt, GetAVModAlt, , true, kParams_OneActorValue_OneOptionalInt);
DEFINE_COMMAND_PLUGIN(RemovePrimitive, , true, nullptr);
DEFINE_COMMAND_PLUGIN(GetPrimitiveType, , true, nullptr);
DEFINE_CMD_ALT_COND_PLUGIN(GetBaseScale, GetBasedScale, , false, kParams_OneOptionalForm);
DEFINE_CMD_ALT_COND_PLUGIN(GetQuestFailed, GetQF, "", false, kParams_OneQuest);
DEFINE_COMMAND_PLUGIN(GetWeaponVATSTraitNumeric, , false, kParams_OneForm_OneInt);
DEFINE_COMMAND_PLUGIN(SetWeaponVATSTraitNumeric, , false, kParams_OneForm_OneInt_OneFloat);
DEFINE_COMMAND_PLUGIN(GetQuestDelay, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(SetNoteRead, , false, kParams_OneForm_OneInt_OneOptionalInt);
DEFINE_COMMAND_PLUGIN(SetMessageIconPath, , false, kParams_OneString_OneForm_OneOptionalInt);
DEFINE_COMMAND_PLUGIN(GetMessageIconPath, , false, kParams_OneForm_OneOptionalInt);
DEFINE_COMMAND_PLUGIN(GetBodyPartTraitString, , false, kParams_OneForm_TwoInts);
DEFINE_COMMAND_PLUGIN(GetActorEffectType, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(GetTalkingActivatorActor, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(GetPlayerKarmaTitle, , false, kParams_OneOptionalInt);
DEFINE_COMMAND_ALT_PLUGIN(FaceGenGetNthProperty, FaceGGetNth, , false, kParams_OneActorBase_TwoInts);
DEFINE_COMMAND_ALT_PLUGIN(FaceGenSetNthProperty, FaceGSetNth, , false, kParams_OneActorBase_TwoInts_OneFloat);
DEFINE_COMMAND_ALT_PLUGIN(FaceGenRefreshAppearance, FaceGRefresh, , true, nullptr);
DEFINE_COMMAND_PLUGIN(GetAvailablePerks, , false, nullptr);
DEFINE_COMMAND_PLUGIN(GetEffectShaderTraitNumeric, , false, kParams_OneForm_OneInt);
DEFINE_COMMAND_PLUGIN(SetEffectShaderTraitNumeric, , false, kParams_OneForm_OneInt_OneFloat);
DEFINE_COMMAND_PLUGIN(GetEffectShaderTexturePath, , false, kParams_OneForm_OneInt);
DEFINE_COMMAND_PLUGIN(SetEffectShaderTexturePath, , false, kParams_OneForm_OneInt_OneString);
DEFINE_COMMAND_PLUGIN(GetArmorAltTextures, , false, kParams_OneForm_OneInt);
DEFINE_COMMAND_PLUGIN(GetIdleMarkerTraitNumeric, , false, kParams_OneForm_OneInt);
DEFINE_COMMAND_PLUGIN(GetIdleMarkerAnimations, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(SetIdleMarkerTraitNumeric, , false, kParams_OneForm_OneInt_OneFloat);
DEFINE_COMMAND_PLUGIN(SetIdleMarkerAnimation, , false, kParams_OneForm_OneInt_OneForm);
DEFINE_COMMAND_PLUGIN(SetIdleMarkerAnimations, , false, kParams_OneForm_OneInt);
DEFINE_COMMAND_PLUGIN(GetWeaponAltTextures, , false, kParams_OneForm);
DEFINE_COMMAND_ALT_PLUGIN(GetRefActivationPromptOverride, GetXATO, , true, nullptr);
DEFINE_COMMAND_ALT_PLUGIN(SetRefActivationPromptOverride, SetXATO, , true, kParams_OneString);
DEFINE_COMMAND_ALT_PLUGIN(GetRefEncounterZone, GetRefZone, , true, nullptr);
DEFINE_COMMAND_ALT_PLUGIN(SetRefEncounterZone, SetRefZone, , true, kParams_OneOptionalForm);
DEFINE_COMMAND_ALT_PLUGIN(SetCellEncounterZone, SetCellZone, , false, kParams_OneForm_OneOptionalForm);
DEFINE_COMMAND_ALT_PLUGIN(GetWorldspaceEncounterZone, GetWorldZone, , false, kParams_OneForm);
DEFINE_COMMAND_ALT_PLUGIN(SetWorldspaceEncounterZone, SetWorldZone, , false, kParams_OneForm_OneOptionalForm);
DEFINE_COMMAND_PLUGIN(GetLightingTemplateTraitNumeric, , false, kParams_OneForm_OneInt);
DEFINE_COMMAND_PLUGIN(SetLightingTemplateTraitNumeric, , false, kParams_OneForm_OneInt_OneFloat);
DEFINE_COMMAND_PLUGIN(GetLightingTemplateCell, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(SetLightingTemplateCell, , false, kParams_TwoForms);
DEFINE_COMMAND_PLUGIN(RemoveScopeModelPath, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(SetArmorAltTexture, , false, kParams_OneForm_TwoInts_OneForm);
DEFINE_COMMAND_PLUGIN(SetWeaponAltTexture, , false, kParams_OneForm_OneInt_OneForm);
DEFINE_COMMAND_PLUGIN(ClearArmorAltTexture, , false, kParams_OneForm_TwoInts);
DEFINE_COMMAND_PLUGIN(ClearWeaponAltTexture, , false, kParams_OneForm_OneInt);
DEFINE_COMMAND_PLUGIN(GetFactionFlags, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(SetFactionFlags, , false, kParams_OneForm_OneInt);
DEFINE_COMMAND_PLUGIN(GetFormRecipesAlt, , false, kParams_OneForm);
DEFINE_CMD_COND_PLUGIN(IsRadioRefPlaying, , true, nullptr);
DEFINE_COMMAND_PLUGIN(TuneRadioRef, , true, kParams_OneOptionalForm);
DEFINE_COMMAND_PLUGIN(HideItemBarterEx, , false, kParams_OneForm_OneInt_OneOptionalInt_OneOptionalForm);
DEFINE_COMMAND_PLUGIN(IsItemBarterHiddenEx, , false, kParams_OneForm_OneOptionalForm);
DEFINE_COMMAND_PLUGIN(GetCurrentFurnitureRef, , true, nullptr);
DEFINE_COMMAND_PLUGIN(GetAltTexturesEx, , false, kParams_OneForm_OneOptionalInt);
DEFINE_COMMAND_PLUGIN(GetNoteSpeaker, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(SetNoteSpeaker, , false, kParams_TwoForms);
DEFINE_COMMAND_PLUGIN(GetNoteType, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(SetNoteType, , false, kParams_OneForm_OneInt);
DEFINE_COMMAND_PLUGIN(GetNoteSound, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(SetNoteSound, , false, kParams_TwoForms);
DEFINE_COMMAND_PLUGIN(GetNoteTopic, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(SetNoteTopic, , false, kParams_TwoForms);
DEFINE_COMMAND_PLUGIN(GetNoteImage, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(SetNoteImage, , false, kParams_OneForm_OneString);
DEFINE_COMMAND_PLUGIN(GetNoteQuestList, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(AddNoteQuest, , false, kParams_TwoForms);
DEFINE_COMMAND_PLUGIN(RemoveNoteQuest, , false, kParams_TwoForms);
DEFINE_COMMAND_PLUGIN(GetHotkeySlot, , true, nullptr);
DEFINE_COMMAND_PLUGIN(GetMineArmedEx, , true, nullptr);
DEFINE_COMMAND_PLUGIN(GetCameraShotTraitNumeric, , false, kParams_OneForm_OneInt);
DEFINE_COMMAND_PLUGIN(SetCameraShotTraitNumeric, , false, kParams_OneForm_OneInt_OneFloat);
DEFINE_COMMAND_PLUGIN(GetCameraShotFlags, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(SetCameraShotFlags, , false, kParams_OneForm_OneInt);
DEFINE_COMMAND_PLUGIN(GetCameraShotPath, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(SetCameraShotPath, , false, kParams_OneForm_OneString);
DEFINE_COMMAND_PLUGIN(GetCameraShotImageSpaceModifier, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(SetCameraShotImageSpaceModifier, , false, kParams_OneForm_OneOptionalForm);
DEFINE_COMMAND_PLUGIN(CallPerRef, , false, kParamsCallPerRef);
DEFINE_COMMAND_PLUGIN_EXP(CallPerRefEx, , false, kParamsCallPerRefEx);
DEFINE_COMMAND_PLUGIN(CallPerMobileObject, , false, kParamsCallPerMobileObject);
DEFINE_COMMAND_PLUGIN_EXP(CallPerMobileObjectEx, , false, kParamsCallPerMobileObjectEx);
DEFINE_COMMAND_PLUGIN(Update3DAlt, , true, kParams_OneInt);
DEFINE_COMMAND_PLUGIN(GetRecipeCategoryFlags, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(RemapLand, , false, kParamsRemapLand);
DEFINE_COMMAND_PLUGIN(GetItemEffectString, , false, kParams_OneOptionalObjectID);
DEFINE_COMMAND_PLUGIN(ApplyModelTextureSwap, , true, kParamsApplyModelTextureSwap);
DEFINE_COMMAND_PLUGIN(SetIKState, , true, kParams_TwoInts);
DEFINE_CMD_COND_PLUGIN(GetIKState, , true, kParams_OneInt);
DEFINE_CMD_COND_PLUGIN(IsCarryable, , false, kParams_OneOptionalObjectID);
DEFINE_COMMAND_PLUGIN(PickIdleEx, , true, kParams_OneRef);
DEFINE_CMD_COND_PLUGIN(GetUsedItemHeight, , false, nullptr);