#pragma once
#include "fn_common.h"

// Functions affecting gameplay
DEFINE_COMMAND_PLUGIN(ToggleLevelUpMenu, , false, kParams_OneInt);
DEFINE_CMD_COND_PLUGIN(IsLevelUpMenuEnabled, , false, nullptr);
DEFINE_COMMAND_PLUGIN(TogglePipBoy, , false, kParams_OneOptionalInt);
DEFINE_COMMAND_PLUGIN(Jump, , true, nullptr);
DEFINE_COMMAND_PLUGIN(StopVATSCam, , false, nullptr);
DEFINE_COMMAND_PLUGIN(SetCameraShake, , false, kParams_TwoFloats);
DEFINE_COMMAND_PLUGIN(ApplyWeaponPoison, , true, kParams_OneOptionalForm);
DEFINE_COMMAND_PLUGIN(SetVelEx, , true, kParams_ThreeFloats);
DEFINE_COMMAND_PLUGIN(StopSoundAlt, , false, kParams_TwoForms_OneOptionalFloat);
DEFINE_COMMAND_PLUGIN(DisableMuzzleFlashLights, , false, kParams_OneOptionalInt);
DEFINE_COMMAND_PLUGIN(UnsetAV, , true, kParams_OneActorValue);
DEFINE_COMMAND_PLUGIN(UnforceAV, , true, kParams_OneActorValue);
DEFINE_COMMAND_PLUGIN(ToggleNthPipboyLight, , false, kParams_TwoInts);
DEFINE_CMD_COND_PLUGIN(GetRunSpeed, , true, nullptr);
DEFINE_COMMAND_PLUGIN(DisableMenuArrowKeys, , false, nullptr);
DEFINE_COMMAND_PLUGIN(EnableMenuArrowKeys, , false, nullptr);
DEFINE_COMMAND_PLUGIN(HighlightBodyPartAlt, , true, kParams_OneOptionalFloat);
DEFINE_COMMAND_PLUGIN(DeactivateAllHighlightsAlt, , true, kParams_OneOptionalFloat);
DEFINE_COMMAND_PLUGIN(RemoveHighlightedRef, , true, nullptr);
DEFINE_COMMAND_PLUGIN(GetNearestCompassHostileDirection, , false, kParams_OneOptionalInt);
DEFINE_COMMAND_PLUGIN(GetNearestCompassHostile, , false, kParams_OneOptionalInt);
DEFINE_COMMAND_ALT_PLUGIN(SetDisablePlayerControlsHUDVisibilityFlags, SetDPCHUDFlags, , false, kParams_OneOptionalInt);
DEFINE_CMD_COND_PLUGIN(IsCompassHostile, , true, nullptr);
DEFINE_COMMAND_PLUGIN(ToggleCombatMusic, , false, kParams_OneInt);
DEFINE_COMMAND_PLUGIN(IsCombatMusicEnabled, , false, nullptr);
DEFINE_COMMAND_PLUGIN(IsHostilesNearby, , false, nullptr);
DEFINE_COMMAND_PLUGIN(ModNthTempEffectTimeLeft, , true, kParams_OneInt_OneFloat);
DEFINE_COMMAND_PLUGIN(GetCalculatedSpread, , true, nullptr);
DEFINE_COMMAND_PLUGIN(SendStealingAlarm, , true, kParams_OneRef_OneOptionalInt);
DEFINE_COMMAND_PLUGIN(GetCompassHostiles, , false, kParams_TwoOptionalInts);
DEFINE_COMMAND_PLUGIN(ToggleDisableSaves, , false, kParams_OneInt_OneOptionalInt);
DEFINE_COMMAND_PLUGIN(SendTrespassAlarmAlt, , true, nullptr);
DEFINE_COMMAND_PLUGIN(IsCrimeOrEnemy, , true, nullptr);
DEFINE_CMD_COND_PLUGIN(GetLocationSpecificLoadScreensOnly, , false, nullptr);
DEFINE_COMMAND_PLUGIN(GetLocationName, , true, nullptr);
DEFINE_COMMAND_PLUGIN(GetPlayingEffectShaders, , true, nullptr);
DEFINE_COMMAND_PLUGIN(StopSoundLooping, , false, kParams_OneForm);
DEFINE_COMMAND_PLUGIN(AddNavmeshObstacle, , true, nullptr);
DEFINE_COMMAND_PLUGIN(RemoveNavmeshObstacle, , true, nullptr);
DEFINE_COMMAND_PLUGIN(GetLandTextureUnderFeet, , true, nullptr);
DEFINE_CMD_COND_PLUGIN(GetMoonPhase, , false, nullptr);
DEFINE_COMMAND_PLUGIN(RewardKarmaAlt, , false, kParams_OneInt);
DEFINE_COMMAND_ALT_PLUGIN(SetCameraShakeNoHUDShudder, CamShakeNHUD , , false, kParams_TwoFloats);
DEFINE_COMMAND_PLUGIN(GetTempIngestibleEffects, , false, nullptr);
DEFINE_COMMAND_PLUGIN(PlaySoundFade, , false, kParams_OneForm_OneFloat);
DEFINE_COMMAND_PLUGIN(GetPointInNavMesh, , false, kParams_ThreeFloats_OneInt_OneOptionalFloat);
DEFINE_COMMAND_PLUGIN(GetNearestNavMeshTriangle, , false, kParams_ThreeFloats_OneInt_OneOptionalFloat);
DEFINE_CMD_COND_PLUGIN(HasHealthDamageEffect, , true, nullptr);
DEFINE_COMMAND_PLUGIN(SetAlwaysRun, , false, kParams_OneInt_OneOptionalInt);
DEFINE_COMMAND_PLUGIN(SetAutoMove, , false, kParams_OneInt_OneOptionalInt);
DEFINE_COMMAND_ALT_PLUGIN(SetActorMovementFlags, SetPlayerMovementFlags, , false, kParams_OneInt);

DEFINE_COMMAND_PLUGIN(SetExtraAccuracyPenaltyMult, , false, kParams_OneFloat_OneOptionalForm);
DEFINE_CMD_COND_PLUGIN(GetExtraAccuracyPenaltyMult, , false, kParams_OneOptionalForm);
DEFINE_COMMAND_PLUGIN(RemoveExtraAccuracyPenaltyMult, , false, kParams_OneOptionalForm);
DEFINE_COMMAND_PLUGIN(SetCustomMapMarker, , false, kParams_ThreeFloats);
DEFINE_COMMAND_PLUGIN(ClearCustomMapMarker, , false, nullptr);
DEFINE_COMMAND_PLUGIN(EjectCasing, , false, kParams_EjectCasing);
DEFINE_COMMAND_PLUGIN(SetHUDShudderPower, , false, kParams_OneFloat);
DEFINE_COMMAND_PLUGIN(GetHUDShudderPower, , false, nullptr);
DEFINE_COMMAND_ALT_PLUGIN(SetMediaLocationControllerOverride, SetMLCOverride, , false, kParams_OneForm);
DEFINE_COMMAND_ALT_PLUGIN(ClearMediaLocationControllerOverride, ClearMLCOverride, , false, nullptr);
DEFINE_COMMAND_ALT_PLUGIN(GetCasinoWinnings, , , false, kParams_OneCasino);
DEFINE_COMMAND_ALT_PLUGIN(SetCasinoWinnings, , , false, kParams_OneCasinoOneInt);
DEFINE_COMMAND_PLUGIN(GetCasinoDeckTexture, , false, kParams_OneCasinoOneInt);
DEFINE_COMMAND_PLUGIN(SetCasinoDeckTexture, , false, kParams_OneCasinoOneIntOneString);
DEFINE_COMMAND_PLUGIN(GetCasinoChip, , false, kParams_OneCasino);
DEFINE_COMMAND_PLUGIN(SetCasinoChip, , false, kParams_OneCasinoOneForm);
DEFINE_COMMAND_PLUGIN(PlayHolotape, , false, kParams_OneForm_OneOptionalInt);
DEFINE_COMMAND_PLUGIN(StopHolotape, , false, kParams_OneOptionalInt);
DEFINE_COMMAND_PLUGIN(PathToRef, , true, kParams_OneRefOneOptionalFloatOneOptionalInt);
DEFINE_CMD_COND_PLUGIN(GetGrenadeHoldTime, , false, nullptr);
DEFINE_COMMAND_PLUGIN(GetWeaponsForMod, , false, kParams_OneObjectID);
DEFINE_CMD_COND_PLUGIN(IsInDialogueWithPlayer, , true, nullptr);
DEFINE_COMMAND_PLUGIN(PathToPoint, , true, kParams_ThreeFloatsTwoOptionalFloats);
DEFINE_COMMAND_PLUGIN(SetYieldTimer, , false, kParams_OneFloat);
DEFINE_CMD_COND_PLUGIN(GetYieldTimer, , false, nullptr);
DEFINE_COMMAND_PLUGIN(GetPCRootWorldspace, , false, nullptr);
DEFINE_CMD_COND_PLUGIN(GetPCInRootWorldspace, , false, kParams_OneWorldSpace);

void RestoreDisabledPlayerControlsHUDFlags();