name: MSBuild

on:
  push:
    branches: [ "dev" ]

env:
  SOLUTION_FILE_PATH: JG/johnnyguitar.sln

permissions: write-all

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
    - uses: actions/checkout@v6

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Release
      run: msbuild /m /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}} /p:PostBuildEventUseInBuild=false

    - name: Build ReleaseDebug
      run: msbuild /m /p:Configuration=ReleaseDebug ${{env.SOLUTION_FILE_PATH}} /p:PostBuildEventUseInBuild=false

    - name: Generate Timestamp
      run: |
        timestamp=$(date +"%Y%m%d%H%M%S")
        echo "artifact_timestamp=$timestamp" >> $GITHUB_ENV
      shell: bash

    - name: Package Artifacts
      run: |
        $iniDir = "JG\assets"
        $releaseDir = "JG\Release"
        $debugDir = "JG\ReleaseDebug"
        New-Item -ItemType Directory -Name artifacts -Force | Out-Null
        New-Item -ItemType Directory -Name "nvse\plugins" -path $releaseDir -Force | Out-Null
        New-Item -ItemType Directory -Name "nvse\plugins" -path $debugDir -Force | Out-Null
        Copy-Item -Path "$releaseDir\johnnyguitar.dll", "$releaseDir\johnnyguitar.pdb", "$iniDir\JohnnyGuitar.ini" -Destination "$releaseDir\nvse\plugins"
        Copy-Item -Path "$debugDir\johnnyguitar.dll", "$debugDir\johnnyguitar.pdb", "$iniDir\JohnnyGuitar.ini" -Destination "$debugDir\nvse\plugins"
        Compress-Archive -Path "$releaseDir\nvse" -DestinationPath "artifacts\JohnnyGuitarNVSE-Release-${{ env.artifact_timestamp }}.zip"
        Compress-Archive -Path "$debugDir\nvse" -DestinationPath "artifacts\JohnnyGuitarNVSE-ReleaseDebug-${{ env.artifact_timestamp }}.zip"
      shell: pwsh

    - name: Publish Zipped Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: Zipped-Artifacts-${{ env.artifact_timestamp }}
        path: artifacts/

    - name: Delete Old Continuous Release
      id: delete_old_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release delete continuous --yes --cleanup-tag
      shell: bash

    - name: Create Continuous Release
      id: create_continuous_release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: continuous
        name: "Continuous release"
        prerelease: true
        allowUpdates: true
        removeArtifacts: true
        generateReleaseNotes: true
        artifacts: artifacts/JohnnyGuitarNVSE-Release-${{ env.artifact_timestamp }}.zip,artifacts/JohnnyGuitarNVSE-ReleaseDebug-${{ env.artifact_timestamp }}.zip
        body: |
          Continuous release generated from the latest push to development branch.

    - name: Upload mod to NexusMods
      id: nexus_upload
      uses: Nexus-Mods/upload-action@main
      continue-on-error: true
      with:
        api_key: ${{ secrets.NEXUSMODS_API_KEY }}
        file_id: ${{ vars.NEXUSMODS_BETA_GROUP_ID }}
        filename: "artifacts\\JohnnyGuitarNVSE-ReleaseDebug-${{ env.artifact_timestamp }}.zip"
        display_name: "JohnnyGuitarNVSE - Continuous Release"
        description: "Auto build from the latest GitHub commit. Use for testing only."
        category: "miscellaneous"
        archive_existing_version: true
        version: ${{ env.artifact_timestamp }}
