name: MSBuild

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  SOLUTION_FILE_PATH: JG/johnnyguitar.sln

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Release
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}} /p:PostBuildEventUseInBuild=false

    - name: Build Debug
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Debug ${{env.SOLUTION_FILE_PATH}} /p:PostBuildEventUseInBuild=false

    - name: Generate Timestamp
      run: |
        timestamp=$(date +"%Y%m%d%H%M%S")
        echo "artifact_timestamp=$timestamp" >> $GITHUB_ENV
      shell: bash

    - name: Publish Release
      uses: actions/upload-artifact@v4
      with:
        name: JohnnyGuitarNVSE-Release-${{ env.artifact_timestamp }}
        path: |
          Release\johnnyguitar.dll

    - name: Publish Debug
      uses: actions/upload-artifact@v4
      with:
        name: JohnnyGuitarNVSE-Debug-${{ env.artifact_timestamp }}
        path: |
          Debug\johnnyguitar.dll