name: MSBuild

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  SOLUTION_FILE_PATH: JG/johnnyguitar.sln

permissions: write-all

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
    - uses: actions/checkout@v6

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Release
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}} /p:PostBuildEventUseInBuild=false

    - name: Build ReleaseDebug
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=ReleaseDebug ${{env.SOLUTION_FILE_PATH}} /p:PostBuildEventUseInBuild=false

    - name: Generate Timestamp
      run: |
        timestamp=$(date +"%Y%m%d%H%M%S")
        echo "artifact_timestamp=$timestamp" >> $GITHUB_ENV
      shell: bash

    - name: Package Artifacts
      run: |
        $releaseDir = "JG\Release"
        $debugDir = "JG\ReleaseDebug"
        New-Item -ItemType Directory -Name artifacts -Force | Out-Null
        New-Item -ItemType Directory -Name "nvse\plugins" -path $releaseDir -Force | Out-Null
        New-Item -ItemType Directory -Name "nvse\plugins" -path $debugDir -Force | Out-Null
        Copy-Item -Path "$releaseDir\johnnyguitar.dll", "$releaseDir\johnnyguitar.pdb" -Destination "$releaseDir\nvse\plugins"
        Copy-Item -Path "$debugDir\johnnyguitar.dll", "$debugDir\johnnyguitar.pdb" -Destination "$debugDir\nvse\plugins"
        Compress-Archive -Path "$releaseDir\nvse" -DestinationPath "artifacts\JohnnyGuitarNVSE-Release-${{ env.artifact_timestamp }}.zip"
        Compress-Archive -Path "$debugDir\nvse" -DestinationPath "artifacts\JohnnyGuitarNVSE-ReleaseDebug-${{ env.artifact_timestamp }}.zip"
      shell: pwsh

    - name: Publish Zipped Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: Zipped-Artifacts-${{ env.artifact_timestamp }}
        path: artifacts/
